/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { Pet } from '../schemas/Pet';

export type AddPetRequestBody = Pet;

export interface AddPetProps extends Omit<RequestInit, 'method' | 'body'> {
	body: AddPetRequestBody;
}

/**
 * Add a new pet to the store
 */
export async function addPet(props: AddPetProps) {
	const { body, ...rest } = props;

	const response = await fetch(`/pet`, {
		method: 'POST',
		body: JSON.stringify(body),
		...rest,
		headers: {
			'Content-Type': 'application/json',
			...rest.headers,
		},
	});

	const json = await response.json();

	return json;
}
