/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface GetPetByIdPathParams {
	/**
	 * @format int64
	 */
	petId: number;
}

export interface GetPetByIdProps
	extends Omit<RequestInit, 'method' | 'body'>,
		GetPetByIdPathParams {}

/**
 * Returns a single pet
 */
export async function getPetById(props: GetPetByIdProps) {
	const { petId, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/pet/${petId}`,
		method: 'GET',
		...rest,
	});
}
