/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

export interface UpdatePetWithFormPathParams {
	/**
	 * @format int64
	 */
	petId: number;
}

export interface UpdatePetWithFormQueryParams {
	name?: string;
	status?: string;
}

export interface UpdatePetWithFormProps
	extends Omit<RequestInit, 'method' | 'body'>,
		UpdatePetWithFormPathParams {
	queryParams: UpdatePetWithFormQueryParams;
}

export async function updatePetWithForm(props: UpdatePetWithFormProps) {
	const { petId, queryParams, ...rest } = props;

	const response = await fetch(`/pet/${petId}`, {
		method: 'POST',
		...rest,
		headers: {
			'Content-Type': 'application/json',
			...rest.headers,
		},
	});

	const json = await response.json();

	return json;
}
