---
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  ecmaFeatures:
    jsx: true
    impliedStrict: true
  project: ./tsconfig-eslint.json
plugins:
  - '@typescript-eslint/eslint-plugin'
env:
  browser: true
  node: true
  shared-node-browser: true
  es6: true
  jest: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
rules:
  # built-in
  semi: [2, 'always']
  no-await-in-loop: 2
  no-shadow: 2

  #typescript
  '@typescript-eslint/no-use-before-define': 0
  '@typescript-eslint/explicit-function-return-type':
    - 1
    - allowExpressions: true
  no-unused-vars: 0
  '@typescript-eslint/no-unused-vars':
    - 2
    - vars: all
      args: after-used
      ignoreRestSiblings: true
      argsIgnorePattern: ^_
  '@typescript-eslint/member-delimiter-style': 0
overrides:
  - files:
      - bin/**/*.js
    rules:
      '@typescript-eslint/no-var-requires': 0
  - files:
      - '**/*.test.ts'
      - '**/*.test.tsx'
    rules:
      '@typescript-eslint/no-magic-numbers': 0
      '@typescript-eslint/no-non-null-assertion': 0
      '@typescript-eslint/no-explicit-any': 0
      '@typescript-eslint/no-non-null-asserted-optional-chain': 0
      no-await-in-loop: 0
      jest/consistent-test-it:
        - 2
        - fn: test
          withinDescribe: test
      jest/expect-expect: 2
      jest/no-disabled-tests: 2
      jest/no-commented-out-tests: 2
