/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ActionsListOrgSecretsQueryParams {
	per_page?: number;
	page?: number;
}

export interface ActionsListOrgSecretsPathParams {
	org: string;
}

export interface ActionsListOrgSecretsProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ActionsListOrgSecretsPathParams {
	queryParams: ActionsListOrgSecretsQueryParams;
}

export async function actionsListOrgSecrets(props: ActionsListOrgSecretsProps) {
	const { org, queryParams, ...rest } = props;

	const response = await fetch(`/orgs/${org}/actions/secrets`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
