/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ActionsListSelfHostedRunnerGroupsForOrgPathParams {
	org: string;
}

export interface ActionsListSelfHostedRunnerGroupsForOrgQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface ActionsListSelfHostedRunnerGroupsForOrgProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ActionsListSelfHostedRunnerGroupsForOrgPathParams {
	queryParams: ActionsListSelfHostedRunnerGroupsForOrgQueryParams;
	paramsSerializer?: (params: ActionsListSelfHostedRunnerGroupsForOrgQueryParams) => string;
}

/**
 * The self-hosted runner groups REST API is available with GitHub Enterprise Cloud. For more information, see "[GitHub's products](https://docs.github.com/github/getting-started-with-github/githubs-products)."
 *
 * Lists all self-hosted runner groups configured in an organization and inherited from an enterprise.
 *
 * You must authenticate using an access token with the `admin:org` scope to use this endpoint.
 */
export async function actionsListSelfHostedRunnerGroupsForOrg(
	props: ActionsListSelfHostedRunnerGroupsForOrgProps,
) {
	const { org, ...rest } = props;

	return _fetcher<unknown, ActionsListSelfHostedRunnerGroupsForOrgQueryParams, unknown>({
		path: `/orgs/${org}/actions/runner-groups`,
		method: 'GET',
		...rest,
	});
}
