/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ActionsListSelfHostedRunnersForRepoQueryParams {
	per_page?: number;
	page?: number;
}

export interface ActionsListSelfHostedRunnersForRepoPathParams {
	owner: string;
	repo: string;
}

export interface ActionsListSelfHostedRunnersForRepoProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ActionsListSelfHostedRunnersForRepoPathParams {
	queryParams: ActionsListSelfHostedRunnersForRepoQueryParams;
}

export async function actionsListSelfHostedRunnersForRepo(
	props: ActionsListSelfHostedRunnersForRepoProps,
) {
	const { owner, repo, queryParams, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/actions/runners`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
