/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ActionsAddSelectedRepoToOrgSecretPathParams {
	org: string;
	secret_name: string;
	repository_id: number;
}

export interface ActionsAddSelectedRepoToOrgSecretProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ActionsAddSelectedRepoToOrgSecretPathParams {}

/**
 * Adds a repository to an organization secret when the `visibility` for repository access is set to `selected`. The visibility is set when you [Create or update an organization secret](https://docs.github.com/rest/reference/actions#create-or-update-an-organization-secret). You must authenticate using an access token with the `admin:org` scope to use this endpoint. GitHub Apps must have the `secrets` organization permission to use this endpoint.
 */
export async function actionsAddSelectedRepoToOrgSecret(
	props: ActionsAddSelectedRepoToOrgSecretProps,
) {
	const { org, secret_name, repository_id, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/orgs/${org}/actions/secrets/${secret_name}/repositories/${repository_id}`,
		method: 'PUT',
		...rest,
	});
}
