/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

export interface ActivityDeleteRepoSubscriptionPathParams {
	owner: string;
	repo: string;
}

export interface ActivityDeleteRepoSubscriptionProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ActivityDeleteRepoSubscriptionPathParams {}

/**
 * This endpoint should only be used to stop watching a repository. To control whether or not you wish to receive notifications from a repository, [set the repository's subscription manually](https://docs.github.com/rest/reference/activity#set-a-repository-subscription).
 */
export async function activityDeleteRepoSubscription(props: ActivityDeleteRepoSubscriptionProps) {
	const { owner, repo, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/subscription`, {
		method: 'DELETE',
		...rest,
		headers: {
			'Content-Type': 'application/json',
			...rest.headers,
		},
	});

	const json = await response.json();

	return json;
}
