/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

export interface ActionsDeleteRepoSecretPathParams {
	owner: string;
	repo: string;
	secret_name: string;
}

export interface ActionsDeleteRepoSecretProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ActionsDeleteRepoSecretPathParams {}

/**
 * Deletes a secret in a repository using the secret name. You must authenticate using an access token with the `repo` scope to use this endpoint. GitHub Apps must have the `secrets` repository permission to use this endpoint.
 */
export async function actionsDeleteRepoSecret(props: ActionsDeleteRepoSecretProps) {
	const { owner, repo, secret_name, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/actions/secrets/${secret_name}`, {
		method: 'DELETE',
		...rest,
		headers: {
			'Content-Type': 'application/json',
			...rest.headers,
		},
	});

	const json = await response.json();

	return json;
}
