/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

export interface ActionsDownloadWorkflowRunLogsPathParams {
	owner: string;
	repo: string;
	run_id: number;
}

export interface ActionsDownloadWorkflowRunLogsProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ActionsDownloadWorkflowRunLogsPathParams {}

/**
 * Gets a redirect URL to download an archive of log files for a workflow run. This link expires after 1 minute. Look for
 * `Location:` in the response header to find the URL for the download. Anyone with read access to the repository can use
 * this endpoint. If the repository is private you must use an access token with the `repo` scope. GitHub Apps must have
 * the `actions:read` permission to use this endpoint.
 */
export async function actionsDownloadWorkflowRunLogs(props: ActionsDownloadWorkflowRunLogsProps) {
	const { owner, repo, run_id, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/actions/runs/${run_id}/logs`, {
		method: 'GET',
		...rest,
		headers: {
			'Content-Type': 'application/json',
			...rest.headers,
		},
	});

	const json = await response.json();

	return json;
}
