/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ActivityGetThreadSubscriptionForAuthenticatedUserPathParams {
	thread_id: number;
}

export interface ActivityGetThreadSubscriptionForAuthenticatedUserProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ActivityGetThreadSubscriptionForAuthenticatedUserPathParams {}

/**
 * This checks to see if the current user is subscribed to a thread. You can also [get a repository subscription](https://docs.github.com/rest/reference/activity#get-a-repository-subscription).
 *
 * Note that subscriptions are only generated if a user is participating in a conversation--for example, they've replied to the thread, were **@mentioned**, or manually subscribe to a thread.
 */
export async function activityGetThreadSubscriptionForAuthenticatedUser(
	props: ActivityGetThreadSubscriptionForAuthenticatedUserProps,
) {
	const { thread_id, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/notifications/threads/${thread_id}/subscription`,
		method: 'GET',
		...rest,
	});
}
