/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ActivityGetThreadSubscriptionForAuthenticatedUserPathParams {
	thread_id: number;
}

export interface ActivityGetThreadSubscriptionForAuthenticatedUserProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ActivityGetThreadSubscriptionForAuthenticatedUserPathParams {}

export async function activityGetThreadSubscriptionForAuthenticatedUser(
	props: ActivityGetThreadSubscriptionForAuthenticatedUserProps,
) {
	const { thread_id, ...rest } = props;

	const response = await fetch(`/notifications/threads/${thread_id}/subscription`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
