/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ActivityListOrgEventsForAuthenticatedUserPathParams {
	username: string;
	org: string;
}

export interface ActivityListOrgEventsForAuthenticatedUserQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface ActivityListOrgEventsForAuthenticatedUserProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ActivityListOrgEventsForAuthenticatedUserPathParams {
	queryParams: ActivityListOrgEventsForAuthenticatedUserQueryParams;
	paramsSerializer?: (params: ActivityListOrgEventsForAuthenticatedUserQueryParams) => string;
}

/**
 * This is the user's organization dashboard. You must be authenticated as the user to view this.
 */
export async function activityListOrgEventsForAuthenticatedUser(
	props: ActivityListOrgEventsForAuthenticatedUserProps,
) {
	const { username, org, ...rest } = props;

	return _fetcher<unknown, ActivityListOrgEventsForAuthenticatedUserQueryParams, unknown>({
		path: `/users/${username}/events/orgs/${org}`,
		method: 'GET',
		...rest,
	});
}
