/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ActionsDeleteOrgSecretPathParams {
	org: string;
	secret_name: string;
}

export interface ActionsDeleteOrgSecretProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ActionsDeleteOrgSecretPathParams {}

export async function actionsDeleteOrgSecret(props: ActionsDeleteOrgSecretProps) {
	const { org, secret_name, ...rest } = props;

	const response = await fetch(`/orgs/${org}/actions/secrets/${secret_name}`, {
		method: 'DELETE',
		...rest,
	});

	const json = await response.json();

	return json;
}
