/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ActionsListRepoAccessToSelfHostedRunnerGroupInOrgQueryParams {
	page?: number;
	per_page?: number;
}

export interface ActionsListRepoAccessToSelfHostedRunnerGroupInOrgPathParams {
	org: string;
	runner_group_id: number;
}

export interface ActionsListRepoAccessToSelfHostedRunnerGroupInOrgProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ActionsListRepoAccessToSelfHostedRunnerGroupInOrgPathParams {
	queryParams: ActionsListRepoAccessToSelfHostedRunnerGroupInOrgQueryParams;
}

export async function actionsListRepoAccessToSelfHostedRunnerGroupInOrg(
	props: ActionsListRepoAccessToSelfHostedRunnerGroupInOrgProps,
) {
	const { org, runner_group_id, queryParams, ...rest } = props;

	const response = await fetch(
		`/orgs/${org}/actions/runner-groups/${runner_group_id}/repositories`,
		{
			method: 'GET',
			...rest,
		},
	);

	const json = await response.json();

	return json;
}
