/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ActionsGetRepoPublicKeyPathParams {
	owner: string;
	repo: string;
}

export interface ActionsGetRepoPublicKeyProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ActionsGetRepoPublicKeyPathParams {}

/**
 * Gets your public key, which you need to encrypt secrets. You need to encrypt a secret before you can create or update secrets. Anyone with read access to the repository can use this endpoint. If the repository is private you must use an access token with the `repo` scope. GitHub Apps must have the `secrets` repository permission to use this endpoint.
 */
export async function actionsGetRepoPublicKey(props: ActionsGetRepoPublicKeyProps) {
	const { owner, repo, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/repos/${owner}/${repo}/actions/secrets/public-key`,
		method: 'GET',
		...rest,
	});
}
