/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ActivityUnstarRepoForAuthenticatedUserPathParams {
	owner: string;
	repo: string;
}

export interface ActivityUnstarRepoForAuthenticatedUserProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ActivityUnstarRepoForAuthenticatedUserPathParams {}

/**
 *
 */
export async function activityUnstarRepoForAuthenticatedUser(
	props: ActivityUnstarRepoForAuthenticatedUserProps,
) {
	const { owner, repo, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/user/starred/${owner}/${repo}`,
		method: 'DELETE',
		...rest,
	});
}
