/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ActivityDeleteThreadSubscriptionPathParams {
	thread_id: number;
}

export interface ActivityDeleteThreadSubscriptionProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ActivityDeleteThreadSubscriptionPathParams {}

/**
 * Mutes all future notifications for a conversation until you comment on the thread or get an **@mention**. If you are watching the repository of the thread, you will still receive notifications. To ignore future notifications for a repository you are watching, use the [Set a thread subscription](https://docs.github.com/rest/reference/activity#set-a-thread-subscription) endpoint and set `ignore` to `true`.
 */
export async function activityDeleteThreadSubscription(
	props: ActivityDeleteThreadSubscriptionProps,
) {
	const { thread_id, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/notifications/threads/${thread_id}/subscription`,
		method: 'DELETE',
		...rest,
	});
}
