/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

export interface ActionsAddSelfHostedRunnerToGroupForOrgPathParams {
	org: string;
	runner_group_id: number;
	runner_id: number;
}

export interface ActionsAddSelfHostedRunnerToGroupForOrgProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ActionsAddSelfHostedRunnerToGroupForOrgPathParams {}

/**
 * The self-hosted runner groups REST API is available with GitHub Enterprise Cloud. For more information, see "[GitHub's products](https://docs.github.com/github/getting-started-with-github/githubs-products)."
 *
 *
 * Adds a self-hosted runner to a runner group configured in an organization.
 *
 * You must authenticate using an access token with the `admin:org`
 * scope to use this endpoint.
 */
export async function actionsAddSelfHostedRunnerToGroupForOrg(
	props: ActionsAddSelfHostedRunnerToGroupForOrgProps,
) {
	const { org, runner_group_id, runner_id, ...rest } = props;

	const response = await fetch(
		`/orgs/${org}/actions/runner-groups/${runner_group_id}/runners/${runner_id}`,
		{
			method: 'PUT',
			...rest,
			headers: {
				'Content-Type': 'application/json',
				...rest.headers,
			},
		},
	);

	const json = await response.json();

	return json;
}
