/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ActivityListEventsForAuthenticatedUserPathParams {
	username: string;
}

export interface ActivityListEventsForAuthenticatedUserQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface ActivityListEventsForAuthenticatedUserProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ActivityListEventsForAuthenticatedUserPathParams {
	queryParams: ActivityListEventsForAuthenticatedUserQueryParams;
	paramsSerializer?: (params: ActivityListEventsForAuthenticatedUserQueryParams) => string;
}

/**
 * If you are authenticated as the given user, you will see your private events. Otherwise, you'll only see public events.
 */
export async function activityListEventsForAuthenticatedUser(
	props: ActivityListEventsForAuthenticatedUserProps,
) {
	const { username, ...rest } = props;

	return _fetcher<unknown, ActivityListEventsForAuthenticatedUserQueryParams, unknown>({
		path: `/users/${username}/events`,
		method: 'GET',
		...rest,
	});
}
