/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ActivityStarRepoForAuthenticatedUserPathParams {
	owner: string;
	repo: string;
}

export interface ActivityStarRepoForAuthenticatedUserProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ActivityStarRepoForAuthenticatedUserPathParams {}

/**
 * Note that you'll need to set `Content-Length` to zero when calling out to this endpoint. For more information, see "[HTTP verbs](https://docs.github.com/rest/overview/resources-in-the-rest-api#http-verbs)."
 */
export async function activityStarRepoForAuthenticatedUser(
	props: ActivityStarRepoForAuthenticatedUserProps,
) {
	const { owner, repo, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/user/starred/${owner}/${repo}`,
		method: 'PUT',
		...rest,
	});
}
