/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

export interface ActionsGetArtifactPathParams {
	owner: string;
	repo: string;
	artifact_id: number;
}

export interface ActionsGetArtifactProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ActionsGetArtifactPathParams {}

/**
 * Gets a specific artifact for a workflow run. Anyone with read access to the repository can use this endpoint. If the repository is private you must use an access token with the `repo` scope. GitHub Apps must have the `actions:read` permission to use this endpoint.
 */
export async function actionsGetArtifact(props: ActionsGetArtifactProps) {
	const { owner, repo, artifact_id, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/actions/artifacts/${artifact_id}`, {
		method: 'GET',
		...rest,
		headers: {
			'Content-Type': 'application/json',
			...rest.headers,
		},
	});

	const json = await response.json();

	return json;
}
