/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

export interface ActionsDownloadJobLogsForWorkflowRunPathParams {
	owner: string;
	repo: string;
	job_id: number;
}

export interface ActionsDownloadJobLogsForWorkflowRunProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ActionsDownloadJobLogsForWorkflowRunPathParams {}

/**
 * Gets a redirect URL to download a plain text file of logs for a workflow job. This link expires after 1 minute. Look
 * for `Location:` in the response header to find the URL for the download. Anyone with read access to the repository can
 * use this endpoint. If the repository is private you must use an access token with the `repo` scope. GitHub Apps must
 * have the `actions:read` permission to use this endpoint.
 */
export async function actionsDownloadJobLogsForWorkflowRun(
	props: ActionsDownloadJobLogsForWorkflowRunProps,
) {
	const { owner, repo, job_id, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/actions/jobs/${job_id}/logs`, {
		method: 'GET',
		...rest,
		headers: {
			'Content-Type': 'application/json',
			...rest.headers,
		},
	});

	const json = await response.json();

	return json;
}
