/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

export interface ActivityListReceivedEventsForUserPathParams {
	username: string;
}

export interface ActivityListReceivedEventsForUserQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface ActivityListReceivedEventsForUserProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ActivityListReceivedEventsForUserPathParams {
	queryParams: ActivityListReceivedEventsForUserQueryParams;
}

/**
 * These are events that you've received by watching repos and following users. If you are authenticated as the given user, you will see private events. Otherwise, you'll only see public events.
 */
export async function activityListReceivedEventsForUser(
	props: ActivityListReceivedEventsForUserProps,
) {
	const { username, queryParams, ...rest } = props;

	const response = await fetch(`/users/${username}/received_events`, {
		method: 'GET',
		...rest,
		headers: {
			'Content-Type': 'application/json',
			...rest.headers,
		},
	});

	const json = await response.json();

	return json;
}
