/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ActionsGetJobForWorkflowRunPathParams {
	owner: string;
	repo: string;
	job_id: number;
}

export interface ActionsGetJobForWorkflowRunProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ActionsGetJobForWorkflowRunPathParams {}

/**
 * Gets a specific job in a workflow run. Anyone with read access to the repository can use this endpoint. If the repository is private you must use an access token with the `repo` scope. GitHub Apps must have the `actions:read` permission to use this endpoint.
 */
export async function actionsGetJobForWorkflowRun(props: ActionsGetJobForWorkflowRunProps) {
	const { owner, repo, job_id, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/repos/${owner}/${repo}/actions/jobs/${job_id}`,
		method: 'GET',
		...rest,
	});
}
