/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ActivityCheckRepoIsStarredByAuthenticatedUserPathParams {
	owner: string;
	repo: string;
}

export interface ActivityCheckRepoIsStarredByAuthenticatedUserProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ActivityCheckRepoIsStarredByAuthenticatedUserPathParams {}

/**
 *
 */
export async function activityCheckRepoIsStarredByAuthenticatedUser(
	props: ActivityCheckRepoIsStarredByAuthenticatedUserProps,
) {
	const { owner, repo, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/user/starred/${owner}/${repo}`,
		method: 'GET',
		...rest,
	});
}
