/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ActionsListWorkflowRunArtifactsQueryParams {
	per_page?: number;
	page?: number;
}

export interface ActionsListWorkflowRunArtifactsPathParams {
	owner: string;
	repo: string;
	run_id: number;
}

export interface ActionsListWorkflowRunArtifactsProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ActionsListWorkflowRunArtifactsPathParams {
	queryParams: ActionsListWorkflowRunArtifactsQueryParams;
}

export async function actionsListWorkflowRunArtifacts(props: ActionsListWorkflowRunArtifactsProps) {
	const { owner, repo, run_id, queryParams, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/actions/runs/${run_id}/artifacts`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
