/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ActionsListOrgSecretsPathParams {
	org: string;
}

export interface ActionsListOrgSecretsQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface ActionsListOrgSecretsProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ActionsListOrgSecretsPathParams {
	queryParams: ActionsListOrgSecretsQueryParams;
	paramsSerializer?: (params: ActionsListOrgSecretsQueryParams) => string;
}

/**
 * Lists all secrets available in an organization without revealing their encrypted values. You must authenticate using an access token with the `admin:org` scope to use this endpoint. GitHub Apps must have the `secrets` organization permission to use this endpoint.
 */
export async function actionsListOrgSecrets(props: ActionsListOrgSecretsProps) {
	const { org, ...rest } = props;

	return _fetcher<unknown, ActionsListOrgSecretsQueryParams, unknown>({
		path: `/orgs/${org}/actions/secrets`,
		method: 'GET',
		...rest,
	});
}
