/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ActivityListWatchersForRepoQueryParams {
	per_page?: number;
	page?: number;
}

export interface ActivityListWatchersForRepoPathParams {
	owner: string;
	repo: string;
}

export interface ActivityListWatchersForRepoProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ActivityListWatchersForRepoPathParams {
	queryParams: ActivityListWatchersForRepoQueryParams;
}

export async function activityListWatchersForRepo(props: ActivityListWatchersForRepoProps) {
	const { owner, repo, queryParams, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/subscribers`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
