/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

export interface ActivityListEventsForAuthenticatedUserPathParams {
	username: string;
}

export interface ActivityListEventsForAuthenticatedUserQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface ActivityListEventsForAuthenticatedUserProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ActivityListEventsForAuthenticatedUserPathParams {
	queryParams: ActivityListEventsForAuthenticatedUserQueryParams;
}

/**
 * If you are authenticated as the given user, you will see your private events. Otherwise, you'll only see public events.
 */
export async function activityListEventsForAuthenticatedUser(
	props: ActivityListEventsForAuthenticatedUserProps,
) {
	const { username, queryParams, ...rest } = props;

	const response = await fetch(`/users/${username}/events`, {
		method: 'GET',
		...rest,
		headers: {
			'Content-Type': 'application/json',
			...rest.headers,
		},
	});

	const json = await response.json();

	return json;
}
