/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface AppsListSubscriptionsForAuthenticatedUserQueryParams {
	per_page?: number;
	page?: number;
}

export interface AppsListSubscriptionsForAuthenticatedUserProps
	extends Omit<RequestInit, 'method' | 'body'> {
	queryParams: AppsListSubscriptionsForAuthenticatedUserQueryParams;
}

export async function appsListSubscriptionsForAuthenticatedUser(
	props: AppsListSubscriptionsForAuthenticatedUserProps,
) {
	const { queryParams, ...rest } = props;

	const response = await fetch(`/user/marketplace_purchases`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
