/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface AppsGetAuthenticatedProps extends Omit<RequestInit, 'method' | 'body'> {}

export async function appsGetAuthenticated(props: AppsGetAuthenticatedProps) {
	const { ...rest } = props;

	const response = await fetch(`/app`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
