/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface AppsAddRepoToInstallationPathParams {
	installation_id: number;
	repository_id: number;
}

export interface AppsAddRepoToInstallationProps
	extends Omit<RequestInit, 'method' | 'body'>,
		AppsAddRepoToInstallationPathParams {}

export async function appsAddRepoToInstallation(props: AppsAddRepoToInstallationProps) {
	const { installation_id, repository_id, ...rest } = props;

	const response = await fetch(
		`/user/installations/${installation_id}/repositories/${repository_id}`,
		{
			method: 'PUT',
			...rest,
		},
	);

	const json = await response.json();

	return json;
}
