/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface AppsListInstallationsQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
	since?: string;
	outdated?: string;
}

export interface AppsListInstallationsProps extends Omit<RequestInit, 'method' | 'body'> {
	queryParams: AppsListInstallationsQueryParams;
	paramsSerializer?: (params: AppsListInstallationsQueryParams) => string;
}

/**
 * You must use a [JWT](https://docs.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app) to access this endpoint.
 *
 * The permissions the installation has are included under the `permissions` key.
 */
export async function appsListInstallations(props: AppsListInstallationsProps) {
	const { ...rest } = props;

	return _fetcher<unknown, AppsListInstallationsQueryParams, unknown>({
		path: `/app/installations`,
		method: 'GET',
		...rest,
	});
}
