/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface AppsListPlansQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface AppsListPlansProps extends Omit<RequestInit, 'method' | 'body'> {
	queryParams: AppsListPlansQueryParams;
	paramsSerializer?: (params: AppsListPlansQueryParams) => string;
}

/**
 * Lists all plans that are part of your GitHub Marketplace listing.
 *
 * GitHub Apps must use a [JWT](https://docs.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app) to access this endpoint. OAuth Apps must use [basic authentication](https://docs.github.com/rest/overview/other-authentication-methods#basic-authentication) with their client ID and client secret to access this endpoint.
 */
export async function appsListPlans(props: AppsListPlansProps) {
	const { ...rest } = props;

	return _fetcher<unknown, AppsListPlansQueryParams, unknown>({
		path: `/marketplace_listing/plans`,
		method: 'GET',
		...rest,
	});
}
