/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface AppsGetSubscriptionPlanForAccountPathParams {
	account_id: number;
}

export interface AppsGetSubscriptionPlanForAccountProps
	extends Omit<RequestInit, 'method' | 'body'>,
		AppsGetSubscriptionPlanForAccountPathParams {}

/**
 * Shows whether the user or organization account actively subscribes to a plan listed by the authenticated GitHub App. When someone submits a plan change that won't be processed until the end of their billing cycle, you will also see the upcoming pending change.
 *
 * GitHub Apps must use a [JWT](https://docs.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app) to access this endpoint. OAuth Apps must use [basic authentication](https://docs.github.com/rest/overview/other-authentication-methods#basic-authentication) with their client ID and client secret to access this endpoint.
 */
export async function appsGetSubscriptionPlanForAccount(
	props: AppsGetSubscriptionPlanForAccountProps,
) {
	const { account_id, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/marketplace_listing/accounts/${account_id}`,
		method: 'GET',
		...rest,
	});
}
