/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface AppsGetInstallationPathParams {
	installation_id: number;
}

export interface AppsGetInstallationProps
	extends Omit<RequestInit, 'method' | 'body'>,
		AppsGetInstallationPathParams {}

/**
 * Enables an authenticated GitHub App to find an installation's information using the installation id. The installation's account type (`target_type`) will be either an organization or a user account, depending which account the repository belongs to.
 *
 * You must use a [JWT](https://docs.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app) to access this endpoint.
 */
export async function appsGetInstallation(props: AppsGetInstallationProps) {
	const { installation_id, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/app/installations/${installation_id}`,
		method: 'GET',
		...rest,
	});
}
