/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface AppsListSubscriptionsForAuthenticatedUserQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface AppsListSubscriptionsForAuthenticatedUserProps
	extends Omit<RequestInit, 'method' | 'body'> {
	queryParams: AppsListSubscriptionsForAuthenticatedUserQueryParams;
	paramsSerializer?: (params: AppsListSubscriptionsForAuthenticatedUserQueryParams) => string;
}

/**
 * Lists the active subscriptions for the authenticated user. You must use a [user-to-server OAuth access token](https://docs.github.com/apps/building-github-apps/identifying-and-authorizing-users-for-github-apps/#identifying-users-on-your-site), created for a user who has authorized your GitHub App, to access this endpoint. . OAuth Apps must authenticate using an [OAuth token](https://docs.github.com/apps/building-github-apps/authenticating-with-github-apps/).
 */
export async function appsListSubscriptionsForAuthenticatedUser(
	props: AppsListSubscriptionsForAuthenticatedUserProps,
) {
	const { ...rest } = props;

	return _fetcher<unknown, AppsListSubscriptionsForAuthenticatedUserQueryParams, unknown>({
		path: `/user/marketplace_purchases`,
		method: 'GET',
		...rest,
	});
}
