/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ChecksUpdatePathParams {
	owner: string;
	repo: string;
	check_run_id: number;
}

export interface ChecksUpdateProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ChecksUpdatePathParams {}

export async function checksUpdate(props: ChecksUpdateProps) {
	const { owner, repo, check_run_id, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/check-runs/${check_run_id}`, {
		method: 'PATCH',
		...rest,
	});

	const json = await response.json();

	return json;
}
