/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface CodesOfConductGetConductCodePathParams {
	key: string;
}

export interface CodesOfConductGetConductCodeProps
	extends Omit<RequestInit, 'method' | 'body'>,
		CodesOfConductGetConductCodePathParams {}

/**
 *
 */
export async function codesOfConductGetConductCode(props: CodesOfConductGetConductCodeProps) {
	const { key, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/codes_of_conduct/${key}`,
		method: 'GET',
		...rest,
	});
}
