/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface CodesOfConductGetConductCodePathParams {
	key: string;
}

export interface CodesOfConductGetConductCodeProps
	extends Omit<RequestInit, 'method' | 'body'>,
		CodesOfConductGetConductCodePathParams {}

export async function codesOfConductGetConductCode(props: CodesOfConductGetConductCodeProps) {
	const { key, ...rest } = props;

	const response = await fetch(`/codes_of_conduct/${key}`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
