/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface EnterpriseAdminDeleteSelfHostedRunnerGroupFromEnterprisePathParams {
	enterprise: string;
	runner_group_id: number;
}

export interface EnterpriseAdminDeleteSelfHostedRunnerGroupFromEnterpriseProps
	extends Omit<RequestInit, 'method' | 'body'>,
		EnterpriseAdminDeleteSelfHostedRunnerGroupFromEnterprisePathParams {}

export async function enterpriseAdminDeleteSelfHostedRunnerGroupFromEnterprise(
	props: EnterpriseAdminDeleteSelfHostedRunnerGroupFromEnterpriseProps,
) {
	const { enterprise, runner_group_id, ...rest } = props;

	const response = await fetch(
		`/enterprises/${enterprise}/actions/runner-groups/${runner_group_id}`,
		{
			method: 'DELETE',
			...rest,
		},
	);

	const json = await response.json();

	return json;
}
