/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface EnterpriseAdminSetInformationForProvisionedEnterpriseGroupPathParams {
	enterprise: string;
	scim_group_id: string;
}

export interface EnterpriseAdminSetInformationForProvisionedEnterpriseGroupProps
	extends Omit<RequestInit, 'method' | 'body'>,
		EnterpriseAdminSetInformationForProvisionedEnterpriseGroupPathParams {}

export async function enterpriseAdminSetInformationForProvisionedEnterpriseGroup(
	props: EnterpriseAdminSetInformationForProvisionedEnterpriseGroupProps,
) {
	const { enterprise, scim_group_id, ...rest } = props;

	const response = await fetch(`/scim/v2/enterprises/${enterprise}/Groups/${scim_group_id}`, {
		method: 'PUT',
		...rest,
	});

	const json = await response.json();

	return json;
}
