/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface EnterpriseAdminGetProvisioningInformationForEnterpriseUserPathParams {
	enterprise: string;
	scim_user_id: string;
}

export interface EnterpriseAdminGetProvisioningInformationForEnterpriseUserProps
	extends Omit<RequestInit, 'method' | 'body'>,
		EnterpriseAdminGetProvisioningInformationForEnterpriseUserPathParams {}

/**
 * **Note:** The SCIM API endpoints for enterprise accounts are currently in beta and are subject to change.
 */
export async function enterpriseAdminGetProvisioningInformationForEnterpriseUser(
	props: EnterpriseAdminGetProvisioningInformationForEnterpriseUserProps,
) {
	const { enterprise, scim_user_id, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/scim/v2/enterprises/${enterprise}/Users/${scim_user_id}`,
		method: 'GET',
		...rest,
	});
}
