/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

export interface EnterpriseAdminEnableSelectedOrganizationGithubActionsEnterprisePathParams {
	enterprise: string;
	org_id: number;
}

export interface EnterpriseAdminEnableSelectedOrganizationGithubActionsEnterpriseProps
	extends Omit<RequestInit, 'method' | 'body'>,
		EnterpriseAdminEnableSelectedOrganizationGithubActionsEnterprisePathParams {}

/**
 * Adds an organization to the list of selected organizations that are enabled for GitHub Actions in an enterprise. To use this endpoint, the enterprise permission policy for `enabled_organizations` must be configured to `selected`. For more information, see "[Set GitHub Actions permissions for an enterprise](#set-github-actions-permissions-for-an-enterprise)."
 *
 * You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export async function enterpriseAdminEnableSelectedOrganizationGithubActionsEnterprise(
	props: EnterpriseAdminEnableSelectedOrganizationGithubActionsEnterpriseProps,
) {
	const { enterprise, org_id, ...rest } = props;

	const response = await fetch(
		`/enterprises/${enterprise}/actions/permissions/organizations/${org_id}`,
		{
			method: 'PUT',
			...rest,
			headers: {
				'Content-Type': 'application/json',
				...rest.headers,
			},
		},
	);

	const json = await response.json();

	return json;
}
