/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface EnterpriseAdminListOrgAccessToSelfHostedRunnerGroupInEnterprisePathParams {
	enterprise: string;
	runner_group_id: number;
}

export interface EnterpriseAdminListOrgAccessToSelfHostedRunnerGroupInEnterpriseQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface EnterpriseAdminListOrgAccessToSelfHostedRunnerGroupInEnterpriseProps
	extends Omit<RequestInit, 'method' | 'body'>,
		EnterpriseAdminListOrgAccessToSelfHostedRunnerGroupInEnterprisePathParams {
	queryParams: EnterpriseAdminListOrgAccessToSelfHostedRunnerGroupInEnterpriseQueryParams;
	paramsSerializer?: (
		params: EnterpriseAdminListOrgAccessToSelfHostedRunnerGroupInEnterpriseQueryParams,
	) => string;
}

/**
 * Lists the organizations with access to a self-hosted runner group.
 *
 * You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export async function enterpriseAdminListOrgAccessToSelfHostedRunnerGroupInEnterprise(
	props: EnterpriseAdminListOrgAccessToSelfHostedRunnerGroupInEnterpriseProps,
) {
	const { enterprise, runner_group_id, ...rest } = props;

	return _fetcher<
		unknown,
		EnterpriseAdminListOrgAccessToSelfHostedRunnerGroupInEnterpriseQueryParams,
		unknown
	>({
		path: `/enterprises/${enterprise}/actions/runner-groups/${runner_group_id}/organizations`,
		method: 'GET',
		...rest,
	});
}
