/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { AllowedActions } from '../schemas/AllowedActions';
import { EnabledOrganizations } from '../schemas/EnabledOrganizations';

export interface EnterpriseAdminSetGithubActionsPermissionsEnterprisePathParams {
	enterprise: string;
}

export interface EnterpriseAdminSetGithubActionsPermissionsEnterpriseRequestBody {
	allowed_actions?: AllowedActions;
	enabled_organizations: EnabledOrganizations;
}

export interface EnterpriseAdminSetGithubActionsPermissionsEnterpriseProps
	extends Omit<RequestInit, 'method' | 'body'>,
		EnterpriseAdminSetGithubActionsPermissionsEnterprisePathParams {
	body: EnterpriseAdminSetGithubActionsPermissionsEnterpriseRequestBody;
}

/**
 * Sets the GitHub Actions permissions policy for organizations and allowed actions in an enterprise.
 *
 * You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export async function enterpriseAdminSetGithubActionsPermissionsEnterprise(
	props: EnterpriseAdminSetGithubActionsPermissionsEnterpriseProps,
) {
	const { enterprise, body, ...rest } = props;

	const response = await fetch(`/enterprises/${enterprise}/actions/permissions`, {
		method: 'PUT',
		body: JSON.stringify(body),
		...rest,
		headers: {
			'Content-Type': 'application/json',
			...rest.headers,
		},
	});

	const json = await response.json();

	return json;
}
