/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface EnterpriseAdminCreateRegistrationTokenForEnterprisePathParams {
	enterprise: string;
}

export interface EnterpriseAdminCreateRegistrationTokenForEnterpriseProps
	extends Omit<RequestInit, 'method' | 'body'>,
		EnterpriseAdminCreateRegistrationTokenForEnterprisePathParams {}

/**
 * Returns a token that you can pass to the `config` script. The token expires after one hour.
 *
 * You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 *
 * #### Example using registration token
 *
 * Configure your self-hosted runner, replacing `TOKEN` with the registration token provided by this endpoint.
 *
 * ```
 * ./config.sh --url https://github.com/enterprises/octo-enterprise --token TOKEN
 * ```
 */
export async function enterpriseAdminCreateRegistrationTokenForEnterprise(
	props: EnterpriseAdminCreateRegistrationTokenForEnterpriseProps,
) {
	const { enterprise, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/enterprises/${enterprise}/actions/runners/registration-token`,
		method: 'POST',
		...rest,
	});
}
