/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface EnterpriseAdminSetOrgAccessToSelfHostedRunnerGroupInEnterprisePathParams {
	enterprise: string;
	runner_group_id: number;
}

export interface EnterpriseAdminSetOrgAccessToSelfHostedRunnerGroupInEnterpriseRequestBody {
	/**
	 * List of organization IDs that can access the runner group.
	 */
	selected_organization_ids: number[];
}

export interface EnterpriseAdminSetOrgAccessToSelfHostedRunnerGroupInEnterpriseProps
	extends Omit<RequestInit, 'method' | 'body'>,
		EnterpriseAdminSetOrgAccessToSelfHostedRunnerGroupInEnterprisePathParams {
	body: EnterpriseAdminSetOrgAccessToSelfHostedRunnerGroupInEnterpriseRequestBody;
}

/**
 * Replaces the list of organizations that have access to a self-hosted runner configured in an enterprise.
 *
 * You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export async function enterpriseAdminSetOrgAccessToSelfHostedRunnerGroupInEnterprise(
	props: EnterpriseAdminSetOrgAccessToSelfHostedRunnerGroupInEnterpriseProps,
) {
	const { enterprise, runner_group_id, ...rest } = props;

	return _fetcher<
		unknown,
		unknown,
		EnterpriseAdminSetOrgAccessToSelfHostedRunnerGroupInEnterpriseRequestBody
	>({
		path: `/enterprises/${enterprise}/actions/runner-groups/${runner_group_id}/organizations`,
		method: 'PUT',
		...rest,
	});
}
