/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

export interface EnterpriseAdminDeleteSelfHostedRunnerGroupFromEnterprisePathParams {
	enterprise: string;
	runner_group_id: number;
}

export interface EnterpriseAdminDeleteSelfHostedRunnerGroupFromEnterpriseProps
	extends Omit<RequestInit, 'method' | 'body'>,
		EnterpriseAdminDeleteSelfHostedRunnerGroupFromEnterprisePathParams {}

/**
 * Deletes a self-hosted runner group for an enterprise.
 *
 * You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export async function enterpriseAdminDeleteSelfHostedRunnerGroupFromEnterprise(
	props: EnterpriseAdminDeleteSelfHostedRunnerGroupFromEnterpriseProps,
) {
	const { enterprise, runner_group_id, ...rest } = props;

	const response = await fetch(
		`/enterprises/${enterprise}/actions/runner-groups/${runner_group_id}`,
		{
			method: 'DELETE',
			...rest,
			headers: {
				'Content-Type': 'application/json',
				...rest.headers,
			},
		},
	);

	const json = await response.json();

	return json;
}
