/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

export interface GistsForkPathParams {
	gist_id: string;
}

export interface GistsForkProps extends Omit<RequestInit, 'method' | 'body'>, GistsForkPathParams {}

/**
 * **Note**: This was previously `/gists/:gist_id/fork`.
 */
export async function gistsFork(props: GistsForkProps) {
	const { gist_id, ...rest } = props;

	const response = await fetch(`/gists/${gist_id}/forks`, {
		method: 'POST',
		...rest,
		headers: {
			'Content-Type': 'application/json',
			...rest.headers,
		},
	});

	const json = await response.json();

	return json;
}
