/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface GistsListForksQueryParams {
	per_page?: number;
	page?: number;
}

export interface GistsListForksPathParams {
	gist_id: string;
}

export interface GistsListForksProps
	extends Omit<RequestInit, 'method' | 'body'>,
		GistsListForksPathParams {
	queryParams: GistsListForksQueryParams;
}

export async function gistsListForks(props: GistsListForksProps) {
	const { gist_id, queryParams, ...rest } = props;

	const response = await fetch(`/gists/${gist_id}/forks`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
