/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface GistsListCommentsQueryParams {
	per_page?: number;
	page?: number;
}

export interface GistsListCommentsPathParams {
	gist_id: string;
}

export interface GistsListCommentsProps
	extends Omit<RequestInit, 'method' | 'body'>,
		GistsListCommentsPathParams {
	queryParams: GistsListCommentsQueryParams;
}

export async function gistsListComments(props: GistsListCommentsProps) {
	const { gist_id, queryParams, ...rest } = props;

	const response = await fetch(`/gists/${gist_id}/comments`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
