/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

export interface GistsListStarredQueryParams {
	since?: string;
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface GistsListStarredProps extends Omit<RequestInit, 'method' | 'body'> {
	queryParams: GistsListStarredQueryParams;
}

/**
 * List the authenticated user's starred gists:
 */
export async function gistsListStarred(props: GistsListStarredProps) {
	const { queryParams, ...rest } = props;

	const response = await fetch(`/gists/starred`, {
		method: 'GET',
		...rest,
		headers: {
			'Content-Type': 'application/json',
			...rest.headers,
		},
	});

	const json = await response.json();

	return json;
}
