/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface GistsCreateCommentPathParams {
	gist_id: string;
}

export interface GistsCreateCommentRequestBody {
	/**
	 * The comment text.
	 * @example "Body of the attachment"
	 */
	body: string;
}

export interface GistsCreateCommentProps
	extends Omit<RequestInit, 'method' | 'body'>,
		GistsCreateCommentPathParams {
	body: GistsCreateCommentRequestBody;
}

/**
 *
 */
export async function gistsCreateComment(props: GistsCreateCommentProps) {
	const { gist_id, ...rest } = props;

	return _fetcher<unknown, unknown, GistsCreateCommentRequestBody>({
		path: `/gists/${gist_id}/comments`,
		method: 'POST',
		...rest,
	});
}
