/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface GistsListQueryParams {
	since?: string;
	per_page?: number;
	page?: number;
}

export interface GistsListProps extends Omit<RequestInit, 'method' | 'body'> {
	queryParams: GistsListQueryParams;
}

export async function gistsList(props: GistsListProps) {
	const { queryParams, ...rest } = props;

	const response = await fetch(`/gists`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
