/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface GitDeleteRefPathParams {
	owner: string;
	repo: string;
	ref: string;
}

export interface GitDeleteRefProps
	extends Omit<RequestInit, 'method' | 'body'>,
		GitDeleteRefPathParams {}

/**
 *
 */
export async function gitDeleteRef(props: GitDeleteRefProps) {
	const { owner, repo, ref, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/repos/${owner}/${repo}/git/refs/${ref}`,
		method: 'DELETE',
		...rest,
	});
}
