/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface IssuesListForAuthenticatedUserQueryParams {
	filter?: 'all' | 'assigned' | 'created' | 'mentioned' | 'repos' | 'subscribed';
	state?: 'all' | 'closed' | 'open';
	labels?: string;
	sort?: 'comments' | 'created' | 'updated';
	direction?: 'asc' | 'desc';
	since?: string;
	per_page?: number;
	page?: number;
}

export interface IssuesListForAuthenticatedUserProps extends Omit<RequestInit, 'method' | 'body'> {
	queryParams: IssuesListForAuthenticatedUserQueryParams;
}

export async function issuesListForAuthenticatedUser(props: IssuesListForAuthenticatedUserProps) {
	const { queryParams, ...rest } = props;

	const response = await fetch(`/user/issues`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
