/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface IssuesListEventsForTimelinePathParams {
	owner: string;
	repo: string;
	issue_number: number;
}

export interface IssuesListEventsForTimelineQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface IssuesListEventsForTimelineProps
	extends Omit<RequestInit, 'method' | 'body'>,
		IssuesListEventsForTimelinePathParams {
	queryParams: IssuesListEventsForTimelineQueryParams;
	paramsSerializer?: (params: IssuesListEventsForTimelineQueryParams) => string;
}

/**
 *
 */
export async function issuesListEventsForTimeline(props: IssuesListEventsForTimelineProps) {
	const { owner, repo, issue_number, ...rest } = props;

	return _fetcher<unknown, IssuesListEventsForTimelineQueryParams, unknown>({
		path: `/repos/${owner}/${repo}/issues/${issue_number}/timeline`,
		method: 'GET',
		...rest,
	});
}
