/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface IssuesListForRepoQueryParams {
	milestone?: string;
	state?: 'all' | 'closed' | 'open';
	assignee?: string;
	creator?: string;
	mentioned?: string;
	labels?: string;
	sort?: 'comments' | 'created' | 'updated';
	direction?: 'asc' | 'desc';
	since?: string;
	per_page?: number;
	page?: number;
}

export interface IssuesListForRepoPathParams {
	owner: string;
	repo: string;
}

export interface IssuesListForRepoProps
	extends Omit<RequestInit, 'method' | 'body'>,
		IssuesListForRepoPathParams {
	queryParams: IssuesListForRepoQueryParams;
}

export async function issuesListForRepo(props: IssuesListForRepoProps) {
	const { owner, repo, queryParams, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/issues`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
