/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface IssuesAddLabelsPathParams {
	owner: string;
	repo: string;
	issue_number: number;
}

export interface IssuesAddLabelsProps
	extends Omit<RequestInit, 'method' | 'body'>,
		IssuesAddLabelsPathParams {}

export async function issuesAddLabels(props: IssuesAddLabelsProps) {
	const { owner, repo, issue_number, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/issues/${issue_number}/labels`, {
		method: 'POST',
		...rest,
	});

	const json = await response.json();

	return json;
}
