/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

export interface IssuesCreateCommentPathParams {
	owner: string;
	repo: string;
	issue_number: number;
}

export interface IssuesCreateCommentRequestBody {
	/**
	 * The contents of the comment.
	 */
	body: string;
}

export interface IssuesCreateCommentProps
	extends Omit<RequestInit, 'method' | 'body'>,
		IssuesCreateCommentPathParams {
	body: IssuesCreateCommentRequestBody;
}

/**
 * This endpoint triggers [notifications](https://docs.github.com/en/github/managing-subscriptions-and-notifications-on-github/about-notifications). Creating content too quickly using this endpoint may result in abuse rate limiting. See "[Abuse rate limits](https://docs.github.com/rest/overview/resources-in-the-rest-api#abuse-rate-limits)" and "[Dealing with abuse rate limits](https://docs.github.com/rest/guides/best-practices-for-integrators#dealing-with-abuse-rate-limits)" for details.
 */
export async function issuesCreateComment(props: IssuesCreateCommentProps) {
	const { owner, repo, issue_number, body, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/issues/${issue_number}/comments`, {
		method: 'POST',
		body: JSON.stringify(body),
		...rest,
		headers: {
			'Content-Type': 'application/json',
			...rest.headers,
		},
	});

	const json = await response.json();

	return json;
}
