/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface LicensesGetAllCommonlyUsedQueryParams {
	featured?: boolean;
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface LicensesGetAllCommonlyUsedProps extends Omit<RequestInit, 'method' | 'body'> {
	queryParams: LicensesGetAllCommonlyUsedQueryParams;
	paramsSerializer?: (params: LicensesGetAllCommonlyUsedQueryParams) => string;
}

/**
 *
 */
export async function licensesGetAllCommonlyUsed(props: LicensesGetAllCommonlyUsedProps) {
	const { ...rest } = props;

	return _fetcher<unknown, LicensesGetAllCommonlyUsedQueryParams, unknown>({
		path: `/licenses`,
		method: 'GET',
		...rest,
	});
}
