/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface LicensesGetAllCommonlyUsedQueryParams {
	featured?: boolean;
	per_page?: number;
	page?: number;
}

export interface LicensesGetAllCommonlyUsedProps extends Omit<RequestInit, 'method' | 'body'> {
	queryParams: LicensesGetAllCommonlyUsedQueryParams;
}

export async function licensesGetAllCommonlyUsed(props: LicensesGetAllCommonlyUsedProps) {
	const { queryParams, ...rest } = props;

	const response = await fetch(`/licenses`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
