/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface MetaGetZenProps extends Omit<RequestInit, 'method' | 'body'> {}

/**
 * Get a random sentence from the Zen of GitHub
 */
export async function metaGetZen(props: MetaGetZenProps) {
	const { ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/zen`,
		method: 'GET',
		...rest,
	});
}
