/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface MigrationsListForAuthenticatedUserQueryParams {
	per_page?: number;
	page?: number;
}

export interface MigrationsListForAuthenticatedUserProps
	extends Omit<RequestInit, 'method' | 'body'> {
	queryParams: MigrationsListForAuthenticatedUserQueryParams;
}

export async function migrationsListForAuthenticatedUser(
	props: MigrationsListForAuthenticatedUserProps,
) {
	const { queryParams, ...rest } = props;

	const response = await fetch(`/user/migrations`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
