/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface MigrationsGetLargeFilesPathParams {
	owner: string;
	repo: string;
}

export interface MigrationsGetLargeFilesProps
	extends Omit<RequestInit, 'method' | 'body'>,
		MigrationsGetLargeFilesPathParams {}

export async function migrationsGetLargeFiles(props: MigrationsGetLargeFilesProps) {
	const { owner, repo, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/import/large_files`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
