/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface MigrationsSetLfsPreferencePathParams {
	owner: string;
	repo: string;
}

export interface MigrationsSetLfsPreferenceProps
	extends Omit<RequestInit, 'method' | 'body'>,
		MigrationsSetLfsPreferencePathParams {}

export async function migrationsSetLfsPreference(props: MigrationsSetLfsPreferenceProps) {
	const { owner, repo, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/import/lfs`, {
		method: 'PATCH',
		...rest,
	});

	const json = await response.json();

	return json;
}
