/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface MigrationsMapCommitAuthorPathParams {
	owner: string;
	repo: string;
	author_id: number;
}

export interface MigrationsMapCommitAuthorProps
	extends Omit<RequestInit, 'method' | 'body'>,
		MigrationsMapCommitAuthorPathParams {}

export async function migrationsMapCommitAuthor(props: MigrationsMapCommitAuthorProps) {
	const { owner, repo, author_id, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/import/authors/${author_id}`, {
		method: 'PATCH',
		...rest,
	});

	const json = await response.json();

	return json;
}
