/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface OauthAuthorizationsUpdateAuthorizationPathParams {
	authorization_id: number;
}

export interface OauthAuthorizationsUpdateAuthorizationProps
	extends Omit<RequestInit, 'method' | 'body'>,
		OauthAuthorizationsUpdateAuthorizationPathParams {}

export async function oauthAuthorizationsUpdateAuthorization(
	props: OauthAuthorizationsUpdateAuthorizationProps,
) {
	const { authorization_id, ...rest } = props;

	const response = await fetch(`/authorizations/${authorization_id}`, {
		method: 'PATCH',
		...rest,
	});

	const json = await response.json();

	return json;
}
