/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface OauthAuthorizationsGetGrantPathParams {
	grant_id: number;
}

export interface OauthAuthorizationsGetGrantProps
	extends Omit<RequestInit, 'method' | 'body'>,
		OauthAuthorizationsGetGrantPathParams {}

export async function oauthAuthorizationsGetGrant(props: OauthAuthorizationsGetGrantProps) {
	const { grant_id, ...rest } = props;

	const response = await fetch(`/applications/grants/${grant_id}`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
