/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface OauthAuthorizationsDeleteAuthorizationPathParams {
	authorization_id: number;
}

export interface OauthAuthorizationsDeleteAuthorizationProps
	extends Omit<RequestInit, 'method' | 'body'>,
		OauthAuthorizationsDeleteAuthorizationPathParams {}

/**
 * **Deprecation Notice:** GitHub will discontinue the [OAuth Authorizations API](https://docs.github.com/rest/reference/oauth-authorizations), which is used by integrations to create personal access tokens and OAuth tokens, and you must now create these tokens using our [web application flow](https://docs.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#web-application-flow). The [OAuth Authorizations API](https://docs.github.com/rest/reference/oauth-authorizations) will be removed on November, 13, 2020. For more information, including scheduled brownouts, see the [blog post](https://developer.github.com/changes/2020-02-14-deprecating-oauth-auth-endpoint/).
 * @deprecated
 */
export async function oauthAuthorizationsDeleteAuthorization(
	props: OauthAuthorizationsDeleteAuthorizationProps,
) {
	const { authorization_id, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/authorizations/${authorization_id}`,
		method: 'DELETE',
		...rest,
	});
}
