/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface OrgsDeleteWebhookPathParams {
	org: string;
	hook_id: number;
}

export interface OrgsDeleteWebhookProps
	extends Omit<RequestInit, 'method' | 'body'>,
		OrgsDeleteWebhookPathParams {}

/**
 *
 */
export async function orgsDeleteWebhook(props: OrgsDeleteWebhookProps) {
	const { org, hook_id, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/orgs/${org}/hooks/${hook_id}`,
		method: 'DELETE',
		...rest,
	});
}
