/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface OrgsListSamlSsoAuthorizationsPathParams {
	org: string;
}

export interface OrgsListSamlSsoAuthorizationsProps
	extends Omit<RequestInit, 'method' | 'body'>,
		OrgsListSamlSsoAuthorizationsPathParams {}

/**
 * Listing and deleting credential authorizations is available to organizations with GitHub Enterprise Cloud. For more information, see [GitHub's products](https://help.github.com/github/getting-started-with-github/githubs-products).
 *
 * An authenticated organization owner with the `read:org` scope can list all credential authorizations for an organization that uses SAML single sign-on (SSO). The credentials are either personal access tokens or SSH keys that organization members have authorized for the organization. For more information, see [About authentication with SAML single sign-on](https://help.github.com/en/articles/about-authentication-with-saml-single-sign-on).
 */
export async function orgsListSamlSsoAuthorizations(props: OrgsListSamlSsoAuthorizationsProps) {
	const { org, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/orgs/${org}/credential-authorizations`,
		method: 'GET',
		...rest,
	});
}
