/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface OrgsRemovePublicMembershipForAuthenticatedUserPathParams {
	org: string;
	username: string;
}

export interface OrgsRemovePublicMembershipForAuthenticatedUserProps
	extends Omit<RequestInit, 'method' | 'body'>,
		OrgsRemovePublicMembershipForAuthenticatedUserPathParams {}

export async function orgsRemovePublicMembershipForAuthenticatedUser(
	props: OrgsRemovePublicMembershipForAuthenticatedUserProps,
) {
	const { org, username, ...rest } = props;

	const response = await fetch(`/orgs/${org}/public_members/${username}`, {
		method: 'DELETE',
		...rest,
	});

	const json = await response.json();

	return json;
}
