/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface OrgsListWebhooksPathParams {
	org: string;
}

export interface OrgsListWebhooksQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface OrgsListWebhooksProps
	extends Omit<RequestInit, 'method' | 'body'>,
		OrgsListWebhooksPathParams {
	queryParams: OrgsListWebhooksQueryParams;
	paramsSerializer?: (params: OrgsListWebhooksQueryParams) => string;
}

/**
 *
 */
export async function orgsListWebhooks(props: OrgsListWebhooksProps) {
	const { org, ...rest } = props;

	return _fetcher<unknown, OrgsListWebhooksQueryParams, unknown>({
		path: `/orgs/${org}/hooks`,
		method: 'GET',
		...rest,
	});
}
