/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface OrgsCancelInvitationPathParams {
	org: string;
	invitation_id: number;
}

export interface OrgsCancelInvitationProps
	extends Omit<RequestInit, 'method' | 'body'>,
		OrgsCancelInvitationPathParams {}

/**
 * Cancel an organization invitation. In order to cancel an organization invitation, the authenticated user must be an organization owner.
 *
 * This endpoint triggers [notifications](https://docs.github.com/en/github/managing-subscriptions-and-notifications-on-github/about-notifications).
 */
export async function orgsCancelInvitation(props: OrgsCancelInvitationProps) {
	const { org, invitation_id, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/orgs/${org}/invitations/${invitation_id}`,
		method: 'DELETE',
		...rest,
	});
}
