/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface OrgsCheckMembershipForUserPathParams {
	org: string;
	username: string;
}

export interface OrgsCheckMembershipForUserProps
	extends Omit<RequestInit, 'method' | 'body'>,
		OrgsCheckMembershipForUserPathParams {}

/**
 * Check if a user is, publicly or privately, a member of the organization.
 */
export async function orgsCheckMembershipForUser(props: OrgsCheckMembershipForUserProps) {
	const { org, username, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/orgs/${org}/members/${username}`,
		method: 'GET',
		...rest,
	});
}
