/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface OrgsListForAuthenticatedUserQueryParams {
	per_page?: number;
	page?: number;
}

export interface OrgsListForAuthenticatedUserProps extends Omit<RequestInit, 'method' | 'body'> {
	queryParams: OrgsListForAuthenticatedUserQueryParams;
}

export async function orgsListForAuthenticatedUser(props: OrgsListForAuthenticatedUserProps) {
	const { queryParams, ...rest } = props;

	const response = await fetch(`/user/orgs`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
