/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface OrgsListAppInstallationsPathParams {
	org: string;
}

export interface OrgsListAppInstallationsQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface OrgsListAppInstallationsProps
	extends Omit<RequestInit, 'method' | 'body'>,
		OrgsListAppInstallationsPathParams {
	queryParams: OrgsListAppInstallationsQueryParams;
	paramsSerializer?: (params: OrgsListAppInstallationsQueryParams) => string;
}

/**
 * Lists all GitHub Apps in an organization. The installation count includes all GitHub Apps installed on repositories in the organization. You must be an organization owner with `admin:read` scope to use this endpoint.
 */
export async function orgsListAppInstallations(props: OrgsListAppInstallationsProps) {
	const { org, ...rest } = props;

	return _fetcher<unknown, OrgsListAppInstallationsQueryParams, unknown>({
		path: `/orgs/${org}/installations`,
		method: 'GET',
		...rest,
	});
}
