/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

export interface OrgsRemoveMembershipForUserPathParams {
	org: string;
	username: string;
}

export interface OrgsRemoveMembershipForUserProps
	extends Omit<RequestInit, 'method' | 'body'>,
		OrgsRemoveMembershipForUserPathParams {}

/**
 * In order to remove a user's membership with an organization, the authenticated user must be an organization owner.
 *
 * If the specified user is an active member of the organization, this will remove them from the organization. If the specified user has been invited to the organization, this will cancel their invitation. The specified user will receive an email notification in both cases.
 */
export async function orgsRemoveMembershipForUser(props: OrgsRemoveMembershipForUserProps) {
	const { org, username, ...rest } = props;

	const response = await fetch(`/orgs/${org}/memberships/${username}`, {
		method: 'DELETE',
		...rest,
		headers: {
			'Content-Type': 'application/json',
			...rest.headers,
		},
	});

	const json = await response.json();

	return json;
}
