/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface OrgsRemoveMemberPathParams {
	org: string;
	username: string;
}

export interface OrgsRemoveMemberProps
	extends Omit<RequestInit, 'method' | 'body'>,
		OrgsRemoveMemberPathParams {}

export async function orgsRemoveMember(props: OrgsRemoveMemberProps) {
	const { org, username, ...rest } = props;

	const response = await fetch(`/orgs/${org}/members/${username}`, {
		method: 'DELETE',
		...rest,
	});

	const json = await response.json();

	return json;
}
