/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

export interface PackagesGetPackageVersionForUserPathParams {
	package_type: 'container' | 'docker' | 'maven' | 'npm' | 'nuget' | 'rubygems';
	package_name: string;
	package_version_id: number;
	username: string;
}

export interface PackagesGetPackageVersionForUserProps
	extends Omit<RequestInit, 'method' | 'body'>,
		PackagesGetPackageVersionForUserPathParams {}

/**
 * Gets a specific package version for a public package owned by a specified user.
 *
 * At this time, to use this endpoint, you must authenticate using an access token with the `packages:read` scope.
 * If `package_type` is not `container`, your token must also include the `repo` scope.
 */
export async function packagesGetPackageVersionForUser(
	props: PackagesGetPackageVersionForUserProps,
) {
	const { package_type, package_name, package_version_id, username, ...rest } = props;

	const response = await fetch(
		`/users/${username}/packages/${package_type}/${package_name}/versions/${package_version_id}`,
		{
			method: 'GET',
			...rest,
			headers: {
				'Content-Type': 'application/json',
				...rest.headers,
			},
		},
	);

	const json = await response.json();

	return json;
}
