/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

export interface PackagesGetPackageForOrganizationPathParams {
	package_type: 'container' | 'docker' | 'maven' | 'npm' | 'nuget' | 'rubygems';
	package_name: string;
	org: string;
}

export interface PackagesGetPackageForOrganizationProps
	extends Omit<RequestInit, 'method' | 'body'>,
		PackagesGetPackageForOrganizationPathParams {}

/**
 * Gets a specific package in an organization.
 *
 * To use this endpoint, you must authenticate using an access token with the `packages:read` scope.
 * If `package_type` is not `container`, your token must also include the `repo` scope.
 */
export async function packagesGetPackageForOrganization(
	props: PackagesGetPackageForOrganizationProps,
) {
	const { package_type, package_name, org, ...rest } = props;

	const response = await fetch(`/orgs/${org}/packages/${package_type}/${package_name}`, {
		method: 'GET',
		...rest,
		headers: {
			'Content-Type': 'application/json',
			...rest.headers,
		},
	});

	const json = await response.json();

	return json;
}
