/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ProjectsRemoveCollaboratorPathParams {
	project_id: number;
	username: string;
}

export interface ProjectsRemoveCollaboratorProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ProjectsRemoveCollaboratorPathParams {}

export async function projectsRemoveCollaborator(props: ProjectsRemoveCollaboratorProps) {
	const { project_id, username, ...rest } = props;

	const response = await fetch(`/projects/${project_id}/collaborators/${username}`, {
		method: 'DELETE',
		...rest,
	});

	const json = await response.json();

	return json;
}
