/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ProjectsDeletePathParams {
	project_id: number;
}

export interface ProjectsDeleteProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ProjectsDeletePathParams {}

/**
 * Deletes a project board. Returns a `404 Not Found` status if projects are disabled.
 */
export async function projectsDelete(props: ProjectsDeleteProps) {
	const { project_id, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/projects/${project_id}`,
		method: 'DELETE',
		...rest,
	});
}
