/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

export interface ProjectsDeletePathParams {
	project_id: number;
}

export interface ProjectsDeleteProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ProjectsDeletePathParams {}

/**
 * Deletes a project board. Returns a `404 Not Found` status if projects are disabled.
 */
export async function projectsDelete(props: ProjectsDeleteProps) {
	const { project_id, ...rest } = props;

	const response = await fetch(`/projects/${project_id}`, {
		method: 'DELETE',
		...rest,
		headers: {
			'Content-Type': 'application/json',
			...rest.headers,
		},
	});

	const json = await response.json();

	return json;
}
