/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ProjectsUpdateColumnPathParams {
	column_id: number;
}

export interface ProjectsUpdateColumnProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ProjectsUpdateColumnPathParams {}

export async function projectsUpdateColumn(props: ProjectsUpdateColumnProps) {
	const { column_id, ...rest } = props;

	const response = await fetch(`/projects/columns/${column_id}`, {
		method: 'PATCH',
		...rest,
	});

	const json = await response.json();

	return json;
}
