/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ProjectsMoveColumnPathParams {
	column_id: number;
}

export interface ProjectsMoveColumnRequestBody {
	/**
	 * The position of the column in a project
	 * @example "last"
	 */
	position: string;
}

export interface ProjectsMoveColumnProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ProjectsMoveColumnPathParams {
	body: ProjectsMoveColumnRequestBody;
}

/**
 *
 */
export async function projectsMoveColumn(props: ProjectsMoveColumnProps) {
	const { column_id, ...rest } = props;

	return _fetcher<unknown, unknown, ProjectsMoveColumnRequestBody>({
		path: `/projects/columns/${column_id}/moves`,
		method: 'POST',
		...rest,
	});
}
