/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ProjectsGetPathParams {
	project_id: number;
}

export interface ProjectsGetProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ProjectsGetPathParams {}

/**
 * Gets a project by its `id`. Returns a `404 Not Found` status if projects are disabled. If you do not have sufficient privileges to perform this action, a `401 Unauthorized` or `410 Gone` status is returned.
 */
export async function projectsGet(props: ProjectsGetProps) {
	const { project_id, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/projects/${project_id}`,
		method: 'GET',
		...rest,
	});
}
