/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ProjectsListForUserPathParams {
	username: string;
}

export interface ProjectsListForUserQueryParams {
	/**
	 * @default "open"
	 */
	state?: 'all' | 'closed' | 'open';
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface ProjectsListForUserProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ProjectsListForUserPathParams {
	queryParams: ProjectsListForUserQueryParams;
	paramsSerializer?: (params: ProjectsListForUserQueryParams) => string;
}

/**
 *
 */
export async function projectsListForUser(props: ProjectsListForUserProps) {
	const { username, ...rest } = props;

	return _fetcher<unknown, ProjectsListForUserQueryParams, unknown>({
		path: `/users/${username}/projects`,
		method: 'GET',
		...rest,
	});
}
