/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ProjectsUpdatePathParams {
	project_id: number;
}

export interface ProjectsUpdateRequestBody {
	/**
	 * Body of the project
	 * @example "This project represents the sprint of the first week in January"
	 */
	body?: string | null;
	/**
	 * Name of the project
	 * @example "Week One Sprint"
	 */
	name?: string;
	/**
	 * The baseline permission that all organization members have on this project
	 */
	organization_permission?: 'admin' | 'none' | 'read' | 'write';
	/**
	 * Whether or not this project can be seen by everyone.
	 */
	private?: boolean;
	/**
	 * State of the project; either 'open' or 'closed'
	 * @example "open"
	 */
	state?: string;
}

export interface ProjectsUpdateProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ProjectsUpdatePathParams {
	body: ProjectsUpdateRequestBody;
}

/**
 * Updates a project board's information. Returns a `404 Not Found` status if projects are disabled. If you do not have sufficient privileges to perform this action, a `401 Unauthorized` or `410 Gone` status is returned.
 */
export async function projectsUpdate(props: ProjectsUpdateProps) {
	const { project_id, ...rest } = props;

	return _fetcher<unknown, unknown, ProjectsUpdateRequestBody>({
		path: `/projects/${project_id}`,
		method: 'PATCH',
		...rest,
	});
}
