/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface PullsCreatePathParams {
	owner: string;
	repo: string;
}

export interface PullsCreateProps
	extends Omit<RequestInit, 'method' | 'body'>,
		PullsCreatePathParams {}

export async function pullsCreate(props: PullsCreateProps) {
	const { owner, repo, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/pulls`, {
		method: 'POST',
		...rest,
	});

	const json = await response.json();

	return json;
}
