/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface PullsCreateReplyForReviewCommentPathParams {
	owner: string;
	repo: string;
	pull_number: number;
	comment_id: number;
}

export interface PullsCreateReplyForReviewCommentProps
	extends Omit<RequestInit, 'method' | 'body'>,
		PullsCreateReplyForReviewCommentPathParams {}

export async function pullsCreateReplyForReviewComment(
	props: PullsCreateReplyForReviewCommentProps,
) {
	const { owner, repo, pull_number, comment_id, ...rest } = props;

	const response = await fetch(
		`/repos/${owner}/${repo}/pulls/${pull_number}/comments/${comment_id}/replies`,
		{
			method: 'POST',
			...rest,
		},
	);

	const json = await response.json();

	return json;
}
