/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface PullsListFilesPathParams {
	owner: string;
	repo: string;
	pull_number: number;
}

export interface PullsListFilesQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface PullsListFilesProps
	extends Omit<RequestInit, 'method' | 'body'>,
		PullsListFilesPathParams {
	queryParams: PullsListFilesQueryParams;
	paramsSerializer?: (params: PullsListFilesQueryParams) => string;
}

/**
 * **Note:** Responses include a maximum of 3000 files. The paginated response returns 30 files per page by default.
 */
export async function pullsListFiles(props: PullsListFilesProps) {
	const { owner, repo, pull_number, ...rest } = props;

	return _fetcher<unknown, PullsListFilesQueryParams, unknown>({
		path: `/repos/${owner}/${repo}/pulls/${pull_number}/files`,
		method: 'GET',
		...rest,
	});
}
