/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface PullsUpdatePathParams {
	owner: string;
	repo: string;
	pull_number: number;
}

export interface PullsUpdateProps
	extends Omit<RequestInit, 'method' | 'body'>,
		PullsUpdatePathParams {}

export async function pullsUpdate(props: PullsUpdateProps) {
	const { owner, repo, pull_number, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/pulls/${pull_number}`, {
		method: 'PATCH',
		...rest,
	});

	const json = await response.json();

	return json;
}
