/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface PullsRequestReviewersPathParams {
	owner: string;
	repo: string;
	pull_number: number;
}

export interface PullsRequestReviewersRequestBody {
	/**
	 * An array of user `login`s that will be requested.
	 */
	reviewers?: string[];
	/**
	 * An array of team `slug`s that will be requested.
	 */
	team_reviewers?: string[];
}

export interface PullsRequestReviewersProps
	extends Omit<RequestInit, 'method' | 'body'>,
		PullsRequestReviewersPathParams {
	body: PullsRequestReviewersRequestBody;
}

/**
 * This endpoint triggers [notifications](https://docs.github.com/github/managing-subscriptions-and-notifications-on-github/about-notifications). Creating content too quickly using this endpoint may result in abuse rate limiting. See "[Abuse rate limits](https://docs.github.com/rest/overview/resources-in-the-rest-api#abuse-rate-limits)" and "[Dealing with abuse rate limits](https://docs.github.com/rest/guides/best-practices-for-integrators#dealing-with-abuse-rate-limits)" for details.
 */
export async function pullsRequestReviewers(props: PullsRequestReviewersProps) {
	const { owner, repo, pull_number, ...rest } = props;

	return _fetcher<unknown, unknown, PullsRequestReviewersRequestBody>({
		path: `/repos/${owner}/${repo}/pulls/${pull_number}/requested_reviewers`,
		method: 'POST',
		...rest,
	});
}
