/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface PullsListReviewsPathParams {
	owner: string;
	repo: string;
	pull_number: number;
}

export interface PullsListReviewsQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface PullsListReviewsProps
	extends Omit<RequestInit, 'method' | 'body'>,
		PullsListReviewsPathParams {
	queryParams: PullsListReviewsQueryParams;
	paramsSerializer?: (params: PullsListReviewsQueryParams) => string;
}

/**
 * The list of reviews returns in chronological order.
 */
export async function pullsListReviews(props: PullsListReviewsProps) {
	const { owner, repo, pull_number, ...rest } = props;

	return _fetcher<unknown, PullsListReviewsQueryParams, unknown>({
		path: `/repos/${owner}/${repo}/pulls/${pull_number}/reviews`,
		method: 'GET',
		...rest,
	});
}
