/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface RateLimitGetProps extends Omit<RequestInit, 'method' | 'body'> {}

/**
 * **Note:** Accessing this endpoint does not count against your REST API rate limit.
 *
 * **Note:** The `rate` object is deprecated. If you're writing new API client code or updating existing code, you should use the `core` object instead of the `rate` object. The `core` object contains the same information that is present in the `rate` object.
 */
export async function rateLimitGet(props: RateLimitGetProps) {
	const { ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/rate_limit`,
		method: 'GET',
		...rest,
	});
}
