/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ReactionsCreateForIssueCommentPathParams {
	owner: string;
	repo: string;
	comment_id: number;
}

export interface ReactionsCreateForIssueCommentProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReactionsCreateForIssueCommentPathParams {}

export async function reactionsCreateForIssueComment(props: ReactionsCreateForIssueCommentProps) {
	const { owner, repo, comment_id, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/issues/comments/${comment_id}/reactions`, {
		method: 'POST',
		...rest,
	});

	const json = await response.json();

	return json;
}
