/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ReactionsListForIssueQueryParams {
	content?: '+1' | '-1' | 'confused' | 'eyes' | 'heart' | 'hooray' | 'laugh' | 'rocket';
	per_page?: number;
	page?: number;
}

export interface ReactionsListForIssuePathParams {
	owner: string;
	repo: string;
	issue_number: number;
}

export interface ReactionsListForIssueProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReactionsListForIssuePathParams {
	queryParams: ReactionsListForIssueQueryParams;
}

export async function reactionsListForIssue(props: ReactionsListForIssueProps) {
	const { owner, repo, issue_number, queryParams, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/issues/${issue_number}/reactions`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
