/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ReactionsCreateForPullRequestReviewCommentPathParams {
	owner: string;
	repo: string;
	comment_id: number;
}

export interface ReactionsCreateForPullRequestReviewCommentRequestBody {
	/**
	 * The [reaction type](https://docs.github.com/rest/reference/reactions#reaction-types) to add to the pull request review comment.
	 */
	content: '+1' | '-1' | 'confused' | 'eyes' | 'heart' | 'hooray' | 'laugh' | 'rocket';
}

export interface ReactionsCreateForPullRequestReviewCommentProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReactionsCreateForPullRequestReviewCommentPathParams {
	body: ReactionsCreateForPullRequestReviewCommentRequestBody;
}

/**
 * Create a reaction to a [pull request review comment](https://docs.github.com/rest/reference/pulls#comments). A response with a `Status: 200 OK` means that you already added the reaction type to this pull request review comment.
 */
export async function reactionsCreateForPullRequestReviewComment(
	props: ReactionsCreateForPullRequestReviewCommentProps,
) {
	const { owner, repo, comment_id, ...rest } = props;

	return _fetcher<unknown, unknown, ReactionsCreateForPullRequestReviewCommentRequestBody>({
		path: `/repos/${owner}/${repo}/pulls/comments/${comment_id}/reactions`,
		method: 'POST',
		...rest,
	});
}
