/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ReactionsListForIssueCommentQueryParams {
	content?: '+1' | '-1' | 'confused' | 'eyes' | 'heart' | 'hooray' | 'laugh' | 'rocket';
	per_page?: number;
	page?: number;
}

export interface ReactionsListForIssueCommentPathParams {
	owner: string;
	repo: string;
	comment_id: number;
}

export interface ReactionsListForIssueCommentProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReactionsListForIssueCommentPathParams {
	queryParams: ReactionsListForIssueCommentQueryParams;
}

export async function reactionsListForIssueComment(props: ReactionsListForIssueCommentProps) {
	const { owner, repo, comment_id, queryParams, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/issues/comments/${comment_id}/reactions`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
