/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ReactionsCreateForIssuePathParams {
	owner: string;
	repo: string;
	issue_number: number;
}

export interface ReactionsCreateForIssueProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReactionsCreateForIssuePathParams {}

export async function reactionsCreateForIssue(props: ReactionsCreateForIssueProps) {
	const { owner, repo, issue_number, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/issues/${issue_number}/reactions`, {
		method: 'POST',
		...rest,
	});

	const json = await response.json();

	return json;
}
