/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ReactionsListForTeamDiscussionLegacyQueryParams {
	content?: '+1' | '-1' | 'confused' | 'eyes' | 'heart' | 'hooray' | 'laugh' | 'rocket';
	per_page?: number;
	page?: number;
}

export interface ReactionsListForTeamDiscussionLegacyPathParams {
	team_id: number;
	discussion_number: number;
}

export interface ReactionsListForTeamDiscussionLegacyProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReactionsListForTeamDiscussionLegacyPathParams {
	queryParams: ReactionsListForTeamDiscussionLegacyQueryParams;
}

export async function reactionsListForTeamDiscussionLegacy(
	props: ReactionsListForTeamDiscussionLegacyProps,
) {
	const { team_id, discussion_number, queryParams, ...rest } = props;

	const response = await fetch(`/teams/${team_id}/discussions/${discussion_number}/reactions`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
