/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ReposCreateForkQueryParams {
	org?: string;
	organization?: string;
}

export interface ReposCreateForkPathParams {
	owner: string;
	repo: string;
}

export interface ReposCreateForkProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposCreateForkPathParams {
	queryParams: ReposCreateForkQueryParams;
}

export async function reposCreateFork(props: ReposCreateForkProps) {
	const { owner, repo, queryParams, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/forks`, {
		method: 'POST',
		...rest,
	});

	const json = await response.json();

	return json;
}
