/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ReposCreateCommitCommentPathParams {
	owner: string;
	repo: string;
	commit_sha: string;
}

export interface ReposCreateCommitCommentProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposCreateCommitCommentPathParams {}

export async function reposCreateCommitComment(props: ReposCreateCommitCommentProps) {
	const { owner, repo, commit_sha, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/commits/${commit_sha}/comments`, {
		method: 'POST',
		...rest,
	});

	const json = await response.json();

	return json;
}
