/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ReposCreateForkPathParams {
	owner: string;
	repo: string;
}

export interface ReposCreateForkQueryParams {
	org?: string;
	organization?: string;
}

export interface ReposCreateForkRequestBody {
	/**
	 * Optional parameter to specify the organization name if forking into an organization.
	 */
	organization?: string;
}

export interface ReposCreateForkProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposCreateForkPathParams {
	queryParams: ReposCreateForkQueryParams;
	paramsSerializer?: (params: ReposCreateForkQueryParams) => string;

	body: ReposCreateForkRequestBody;
}

/**
 * Create a fork for the authenticated user.
 *
 * **Note**: Forking a Repository happens asynchronously. You may have to wait a short period of time before you can access the git objects. If this takes longer than 5 minutes, be sure to contact [GitHub Support](https://support.github.com/contact) or [GitHub Premium Support](https://premium.githubsupport.com).
 */
export async function reposCreateFork(props: ReposCreateForkProps) {
	const { owner, repo, ...rest } = props;

	return _fetcher<unknown, ReposCreateForkQueryParams, ReposCreateForkRequestBody>({
		path: `/repos/${owner}/${repo}/forks`,
		method: 'POST',
		...rest,
	});
}
