/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ReposReplaceAllTopicsPathParams {
	owner: string;
	repo: string;
}

export interface ReposReplaceAllTopicsProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposReplaceAllTopicsPathParams {}

export async function reposReplaceAllTopics(props: ReposReplaceAllTopicsProps) {
	const { owner, repo, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/topics`, {
		method: 'PUT',
		...rest,
	});

	const json = await response.json();

	return json;
}
