/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ReposGetDeploymentStatusPathParams {
	owner: string;
	repo: string;
	deployment_id: number;
	status_id: number;
}

export interface ReposGetDeploymentStatusProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposGetDeploymentStatusPathParams {}

/**
 * Users with pull access can view a deployment status for a deployment:
 */
export async function reposGetDeploymentStatus(props: ReposGetDeploymentStatusProps) {
	const { owner, repo, deployment_id, status_id, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/repos/${owner}/${repo}/deployments/${deployment_id}/statuses/${status_id}`,
		method: 'GET',
		...rest,
	});
}
