/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

export interface ReposGetAllEnvironmentsPathParams {
	owner: string;
	repo: string;
}

export interface ReposGetAllEnvironmentsProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposGetAllEnvironmentsPathParams {}

/**
 * Get all environments for a repository.
 *
 * Anyone with read access to the repository can use this endpoint. If the repository is private, you must use an access token with the `repo` scope. GitHub Apps must have the `actions:read` permission to use this endpoint.
 */
export async function reposGetAllEnvironments(props: ReposGetAllEnvironmentsProps) {
	const { owner, repo, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/environments`, {
		method: 'GET',
		...rest,
		headers: {
			'Content-Type': 'application/json',
			...rest.headers,
		},
	});

	const json = await response.json();

	return json;
}
