/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ReposUpdateCommitCommentPathParams {
	owner: string;
	repo: string;
	comment_id: number;
}

export interface ReposUpdateCommitCommentRequestBody {
	/**
	 * The contents of the comment
	 */
	body: string;
}

export interface ReposUpdateCommitCommentProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposUpdateCommitCommentPathParams {
	body: ReposUpdateCommitCommentRequestBody;
}

/**
 *
 */
export async function reposUpdateCommitComment(props: ReposUpdateCommitCommentProps) {
	const { owner, repo, comment_id, ...rest } = props;

	return _fetcher<unknown, unknown, ReposUpdateCommitCommentRequestBody>({
		path: `/repos/${owner}/${repo}/comments/${comment_id}`,
		method: 'PATCH',
		...rest,
	});
}
