/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ReposSetStatusCheckContextsPathParams {
	owner: string;
	repo: string;
	branch: string;
}

/**
 * @example {"contexts":["contexts"]}
 */
export interface ReposSetStatusCheckContextsRequestBody {
	/**
	 * contexts parameter
	 */
	contexts: string[];
}

export interface ReposSetStatusCheckContextsProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposSetStatusCheckContextsPathParams {
	body: ReposSetStatusCheckContextsRequestBody;
}

/**
 * Protected branches are available in public repositories with GitHub Free and GitHub Free for organizations, and in public and private repositories with GitHub Pro, GitHub Team, GitHub Enterprise Cloud, and GitHub Enterprise Server. For more information, see [GitHub's products](https://help.github.com/github/getting-started-with-github/githubs-products) in the GitHub Help documentation.
 */
export async function reposSetStatusCheckContexts(props: ReposSetStatusCheckContextsProps) {
	const { owner, repo, branch, ...rest } = props;

	return _fetcher<unknown, unknown, ReposSetStatusCheckContextsRequestBody>({
		path: `/repos/${owner}/${repo}/branches/${branch}/protection/required_status_checks/contexts`,
		method: 'PUT',
		...rest,
	});
}
