/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ReposAcceptInvitationPathParams {
	invitation_id: number;
}

export interface ReposAcceptInvitationProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposAcceptInvitationPathParams {}

export async function reposAcceptInvitation(props: ReposAcceptInvitationProps) {
	const { invitation_id, ...rest } = props;

	const response = await fetch(`/user/repository_invitations/${invitation_id}`, {
		method: 'PATCH',
		...rest,
	});

	const json = await response.json();

	return json;
}
