/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

export interface ReposGetReleasePathParams {
	owner: string;
	repo: string;
	release_id: number;
}

export interface ReposGetReleaseProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposGetReleasePathParams {}

/**
 * **Note:** This returns an `upload_url` key corresponding to the endpoint for uploading release assets. This key is a [hypermedia resource](https://docs.github.com/rest/overview/resources-in-the-rest-api#hypermedia).
 */
export async function reposGetRelease(props: ReposGetReleaseProps) {
	const { owner, repo, release_id, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/releases/${release_id}`, {
		method: 'GET',
		...rest,
		headers: {
			'Content-Type': 'application/json',
			...rest.headers,
		},
	});

	const json = await response.json();

	return json;
}
