/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ReposAcceptInvitationPathParams {
	invitation_id: number;
}

export interface ReposAcceptInvitationProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposAcceptInvitationPathParams {}

/**
 *
 */
export async function reposAcceptInvitation(props: ReposAcceptInvitationProps) {
	const { invitation_id, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/user/repository_invitations/${invitation_id}`,
		method: 'PATCH',
		...rest,
	});
}
