/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ReposGetReleasePathParams {
	owner: string;
	repo: string;
	release_id: number;
}

export interface ReposGetReleaseProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposGetReleasePathParams {}

/**
 * **Note:** This returns an `upload_url` key corresponding to the endpoint for uploading release assets. This key is a [hypermedia resource](https://docs.github.com/rest/overview/resources-in-the-rest-api#hypermedia).
 */
export async function reposGetRelease(props: ReposGetReleaseProps) {
	const { owner, repo, release_id, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/repos/${owner}/${repo}/releases/${release_id}`,
		method: 'GET',
		...rest,
	});
}
