/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ReposUpdateInvitationPathParams {
	owner: string;
	repo: string;
	invitation_id: number;
}

export interface ReposUpdateInvitationProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposUpdateInvitationPathParams {}

export async function reposUpdateInvitation(props: ReposUpdateInvitationProps) {
	const { owner, repo, invitation_id, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/invitations/${invitation_id}`, {
		method: 'PATCH',
		...rest,
	});

	const json = await response.json();

	return json;
}
