/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ReposGetViewsPathParams {
	owner: string;
	repo: string;
}

export interface ReposGetViewsQueryParams {
	/**
	 * @default "day"
	 */
	per?: '' | 'day' | 'week';
}

export interface ReposGetViewsProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposGetViewsPathParams {
	queryParams: ReposGetViewsQueryParams;
	paramsSerializer?: (params: ReposGetViewsQueryParams) => string;
}

/**
 * Get the total number of views and breakdown per day or week for the last 14 days. Timestamps are aligned to UTC midnight of the beginning of the day or week. Week begins on Monday.
 */
export async function reposGetViews(props: ReposGetViewsProps) {
	const { owner, repo, ...rest } = props;

	return _fetcher<unknown, ReposGetViewsQueryParams, unknown>({
		path: `/repos/${owner}/${repo}/traffic/views`,
		method: 'GET',
		...rest,
	});
}
