/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ReposGetLatestReleasePathParams {
	owner: string;
	repo: string;
}

export interface ReposGetLatestReleaseProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposGetLatestReleasePathParams {}

export async function reposGetLatestRelease(props: ReposGetLatestReleaseProps) {
	const { owner, repo, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/releases/latest`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
