/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ReposGetCommitCommentPathParams {
	owner: string;
	repo: string;
	comment_id: number;
}

export interface ReposGetCommitCommentProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposGetCommitCommentPathParams {}

/**
 *
 */
export async function reposGetCommitComment(props: ReposGetCommitCommentProps) {
	const { owner, repo, comment_id, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/repos/${owner}/${repo}/comments/${comment_id}`,
		method: 'GET',
		...rest,
	});
}
