/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ReposAddStatusCheckContextsPathParams {
	owner: string;
	repo: string;
	branch: string;
}

export interface ReposAddStatusCheckContextsProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposAddStatusCheckContextsPathParams {}

export async function reposAddStatusCheckContexts(props: ReposAddStatusCheckContextsProps) {
	const { owner, repo, branch, ...rest } = props;

	const response = await fetch(
		`/repos/${owner}/${repo}/branches/${branch}/protection/required_status_checks/contexts`,
		{
			method: 'POST',
			...rest,
		},
	);

	const json = await response.json();

	return json;
}
