/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ReposGetCommitQueryParams {
	page?: number;
	per_page?: number;
}

export interface ReposGetCommitPathParams {
	owner: string;
	repo: string;
	ref: string;
}

export interface ReposGetCommitProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposGetCommitPathParams {
	queryParams: ReposGetCommitQueryParams;
}

export async function reposGetCommit(props: ReposGetCommitProps) {
	const { owner, repo, ref, queryParams, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/commits/${ref}`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
