/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ReposGetEnvironmentPathParams {
	owner: string;
	repo: string;
	environment_name: string;
}

export interface ReposGetEnvironmentProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposGetEnvironmentPathParams {}

/**
 * Anyone with read access to the repository can use this endpoint. If the repository is private, you must use an access token with the `repo` scope. GitHub Apps must have the `actions:read` permission to use this endpoint.
 */
export async function reposGetEnvironment(props: ReposGetEnvironmentProps) {
	const { owner, repo, environment_name, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/repos/${owner}/${repo}/environments/${environment_name}`,
		method: 'GET',
		...rest,
	});
}
