/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ReposGetBranchPathParams {
	owner: string;
	repo: string;
	branch: string;
}

export interface ReposGetBranchProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposGetBranchPathParams {}

/**
 *
 */
export async function reposGetBranch(props: ReposGetBranchProps) {
	const { owner, repo, branch, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/repos/${owner}/${repo}/branches/${branch}`,
		method: 'GET',
		...rest,
	});
}
