/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ReposListDeployKeysPathParams {
	owner: string;
	repo: string;
}

export interface ReposListDeployKeysQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface ReposListDeployKeysProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposListDeployKeysPathParams {
	queryParams: ReposListDeployKeysQueryParams;
	paramsSerializer?: (params: ReposListDeployKeysQueryParams) => string;
}

/**
 *
 */
export async function reposListDeployKeys(props: ReposListDeployKeysProps) {
	const { owner, repo, ...rest } = props;

	return _fetcher<unknown, ReposListDeployKeysQueryParams, unknown>({
		path: `/repos/${owner}/${repo}/keys`,
		method: 'GET',
		...rest,
	});
}
