/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ReposListForAuthenticatedUserQueryParams {
	visibility?: 'all' | 'private' | 'public';
	affiliation?: string;
	type?: 'all' | 'member' | 'owner' | 'private' | 'public';
	sort?: 'created' | 'full_name' | 'pushed' | 'updated';
	direction?: 'asc' | 'desc';
	per_page?: number;
	page?: number;
	since?: string;
	before?: string;
}

export interface ReposListForAuthenticatedUserProps extends Omit<RequestInit, 'method' | 'body'> {
	queryParams: ReposListForAuthenticatedUserQueryParams;
}

export async function reposListForAuthenticatedUser(props: ReposListForAuthenticatedUserProps) {
	const { queryParams, ...rest } = props;

	const response = await fetch(`/user/repos`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
