/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

export interface ReposGetLatestReleasePathParams {
	owner: string;
	repo: string;
}

export interface ReposGetLatestReleaseProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposGetLatestReleasePathParams {}

/**
 * View the latest published full release for the repository.
 *
 * The latest release is the most recent non-prerelease, non-draft release, sorted by the `created_at` attribute. The `created_at` attribute is the date of the commit used for the release, and not the date when the release was drafted or published.
 */
export async function reposGetLatestRelease(props: ReposGetLatestReleaseProps) {
	const { owner, repo, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/releases/latest`, {
		method: 'GET',
		...rest,
		headers: {
			'Content-Type': 'application/json',
			...rest.headers,
		},
	});

	const json = await response.json();

	return json;
}
