/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ReposGetReadmeFromAltPathPathParams {
	owner: string;
	repo: string;
	dir: string;
}

export interface ReposGetReadmeFromAltPathQueryParams {
	ref?: string;
}

export interface ReposGetReadmeFromAltPathProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposGetReadmeFromAltPathPathParams {
	queryParams: ReposGetReadmeFromAltPathQueryParams;
	paramsSerializer?: (params: ReposGetReadmeFromAltPathQueryParams) => string;
}

/**
 * Gets the preferred README for a repository.
 *
 * READMEs support [custom media types](https://docs.github.com/rest/reference/repos#custom-media-types) for retrieving the raw content or rendered HTML.
 */
export async function reposGetReadmeFromAltPath(props: ReposGetReadmeFromAltPathProps) {
	const { owner, repo, dir, ...rest } = props;

	return _fetcher<unknown, ReposGetReadmeFromAltPathQueryParams, unknown>({
		path: `/repos/${owner}/${repo}/readme/${dir}`,
		method: 'GET',
		...rest,
	});
}
