/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ReposDeleteCommitSignatureProtectionPathParams {
	owner: string;
	repo: string;
	branch: string;
}

export interface ReposDeleteCommitSignatureProtectionProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposDeleteCommitSignatureProtectionPathParams {}

export async function reposDeleteCommitSignatureProtection(
	props: ReposDeleteCommitSignatureProtectionProps,
) {
	const { owner, repo, branch, ...rest } = props;

	const response = await fetch(
		`/repos/${owner}/${repo}/branches/${branch}/protection/required_signatures`,
		{
			method: 'DELETE',
			...rest,
		},
	);

	const json = await response.json();

	return json;
}
