/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

export interface ReposListLanguagesPathParams {
	owner: string;
	repo: string;
}

export interface ReposListLanguagesProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposListLanguagesPathParams {}

/**
 * Lists languages for the specified repository. The value shown for each language is the number of bytes of code written in that language.
 */
export async function reposListLanguages(props: ReposListLanguagesProps) {
	const { owner, repo, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/languages`, {
		method: 'GET',
		...rest,
		headers: {
			'Content-Type': 'application/json',
			...rest.headers,
		},
	});

	const json = await response.json();

	return json;
}
