/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ReposListCommitsQueryParams {
	sha?: string;
	path?: string;
	author?: string;
	since?: string;
	until?: string;
	per_page?: number;
	page?: number;
	top?: string;
	last_sha?: string;
}

export interface ReposListCommitsPathParams {
	owner: string;
	repo: string;
}

export interface ReposListCommitsProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposListCommitsPathParams {
	queryParams: ReposListCommitsQueryParams;
}

export async function reposListCommits(props: ReposListCommitsProps) {
	const { owner, repo, queryParams, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/commits`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
