/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ReposCreatePagesSitePathParams {
	owner: string;
	repo: string;
}

export interface ReposCreatePagesSiteProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposCreatePagesSitePathParams {}

export async function reposCreatePagesSite(props: ReposCreatePagesSiteProps) {
	const { owner, repo, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/pages`, {
		method: 'POST',
		...rest,
	});

	const json = await response.json();

	return json;
}
