/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface ReposDeletePathParams {
	owner: string;
	repo: string;
}

export interface ReposDeleteProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposDeletePathParams {}

/**
 * Deleting a repository requires admin access. If OAuth is used, the `delete_repo` scope is required.
 *
 * If an organization owner has configured the organization to prevent members from deleting organization-owned
 * repositories, you will get a `403 Forbidden` response.
 */
export async function reposDelete(props: ReposDeleteProps) {
	const { owner, repo, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/repos/${owner}/${repo}`,
		method: 'DELETE',
		...rest,
	});
}
