/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ReposUpdateReleasePathParams {
	owner: string;
	repo: string;
	release_id: number;
}

export interface ReposUpdateReleaseProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposUpdateReleasePathParams {}

export async function reposUpdateRelease(props: ReposUpdateReleaseProps) {
	const { owner, repo, release_id, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/releases/${release_id}`, {
		method: 'PATCH',
		...rest,
	});

	const json = await response.json();

	return json;
}
