/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ReposUpdateWebhookConfigForRepoPathParams {
	owner: string;
	repo: string;
	hook_id: number;
}

export interface ReposUpdateWebhookConfigForRepoProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ReposUpdateWebhookConfigForRepoPathParams {}

export async function reposUpdateWebhookConfigForRepo(props: ReposUpdateWebhookConfigForRepoProps) {
	const { owner, repo, hook_id, ...rest } = props;

	const response = await fetch(`/repos/${owner}/${repo}/hooks/${hook_id}/config`, {
		method: 'PATCH',
		...rest,
	});

	const json = await response.json();

	return json;
}
