/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface ScimListProvisionedIdentitiesQueryParams {
	startIndex?: number;
	count?: number;
	filter?: string;
}

export interface ScimListProvisionedIdentitiesPathParams {
	org: string;
}

export interface ScimListProvisionedIdentitiesProps
	extends Omit<RequestInit, 'method' | 'body'>,
		ScimListProvisionedIdentitiesPathParams {
	queryParams: ScimListProvisionedIdentitiesQueryParams;
}

export async function scimListProvisionedIdentities(props: ScimListProvisionedIdentitiesProps) {
	const { org, queryParams, ...rest } = props;

	const response = await fetch(`/scim/v2/organizations/${org}/Users`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
