/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface TeamsDeleteInOrgPathParams {
	org: string;
	team_slug: string;
}

export interface TeamsDeleteInOrgProps
	extends Omit<RequestInit, 'method' | 'body'>,
		TeamsDeleteInOrgPathParams {}

/**
 * To delete a team, the authenticated user must be an organization owner or team maintainer.
 *
 * If you are an organization owner, deleting a parent team will delete all of its child teams as well.
 *
 * **Note:** You can also specify a team by `org_id` and `team_id` using the route `DELETE /organizations/{org_id}/team/{team_id}`.
 */
export async function teamsDeleteInOrg(props: TeamsDeleteInOrgProps) {
	const { org, team_slug, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/orgs/${org}/teams/${team_slug}`,
		method: 'DELETE',
		...rest,
	});
}
