/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface TeamsUpdateDiscussionLegacyPathParams {
	team_id: number;
	discussion_number: number;
}

export interface TeamsUpdateDiscussionLegacyRequestBody {
	/**
	 * The discussion post's body text.
	 */
	body?: string;
	/**
	 * The discussion post's title.
	 */
	title?: string;
}

export interface TeamsUpdateDiscussionLegacyProps
	extends Omit<RequestInit, 'method' | 'body'>,
		TeamsUpdateDiscussionLegacyPathParams {
	body: TeamsUpdateDiscussionLegacyRequestBody;
}

/**
 * **Deprecation Notice:** This endpoint route is deprecated and will be removed from the Teams API. We recommend migrating your existing code to use the new [Update a discussion](https://docs.github.com/rest/reference/teams#update-a-discussion) endpoint.
 *
 * Edits the title and body text of a discussion post. Only the parameters you provide are updated. OAuth access tokens require the `write:discussion` [scope](https://docs.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/).
 * @deprecated
 */
export async function teamsUpdateDiscussionLegacy(props: TeamsUpdateDiscussionLegacyProps) {
	const { team_id, discussion_number, ...rest } = props;

	return _fetcher<unknown, unknown, TeamsUpdateDiscussionLegacyRequestBody>({
		path: `/teams/${team_id}/discussions/${discussion_number}`,
		method: 'PATCH',
		...rest,
	});
}
