/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface TeamsListChildLegacyPathParams {
	team_id: number;
}

export interface TeamsListChildLegacyQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface TeamsListChildLegacyProps
	extends Omit<RequestInit, 'method' | 'body'>,
		TeamsListChildLegacyPathParams {
	queryParams: TeamsListChildLegacyQueryParams;
	paramsSerializer?: (params: TeamsListChildLegacyQueryParams) => string;
}

/**
 * **Deprecation Notice:** This endpoint route is deprecated and will be removed from the Teams API. We recommend migrating your existing code to use the new [`List child teams`](https://docs.github.com/rest/reference/teams#list-child-teams) endpoint.
 * @deprecated
 */
export async function teamsListChildLegacy(props: TeamsListChildLegacyProps) {
	const { team_id, ...rest } = props;

	return _fetcher<unknown, TeamsListChildLegacyQueryParams, unknown>({
		path: `/teams/${team_id}/teams`,
		method: 'GET',
		...rest,
	});
}
