/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface TeamsAddOrUpdateMembershipForUserInOrgPathParams {
	org: string;
	team_slug: string;
	username: string;
}

export interface TeamsAddOrUpdateMembershipForUserInOrgProps
	extends Omit<RequestInit, 'method' | 'body'>,
		TeamsAddOrUpdateMembershipForUserInOrgPathParams {}

export async function teamsAddOrUpdateMembershipForUserInOrg(
	props: TeamsAddOrUpdateMembershipForUserInOrgProps,
) {
	const { org, team_slug, username, ...rest } = props;

	const response = await fetch(`/orgs/${org}/teams/${team_slug}/memberships/${username}`, {
		method: 'PUT',
		...rest,
	});

	const json = await response.json();

	return json;
}
