/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface TeamsAddOrUpdateProjectPermissionsInOrgPathParams {
	org: string;
	team_slug: string;
	project_id: number;
}

export interface TeamsAddOrUpdateProjectPermissionsInOrgProps
	extends Omit<RequestInit, 'method' | 'body'>,
		TeamsAddOrUpdateProjectPermissionsInOrgPathParams {}

export async function teamsAddOrUpdateProjectPermissionsInOrg(
	props: TeamsAddOrUpdateProjectPermissionsInOrgProps,
) {
	const { org, team_slug, project_id, ...rest } = props;

	const response = await fetch(`/orgs/${org}/teams/${team_slug}/projects/${project_id}`, {
		method: 'PUT',
		...rest,
	});

	const json = await response.json();

	return json;
}
