/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface TeamsListProjectsInOrgPathParams {
	org: string;
	team_slug: string;
}

export interface TeamsListProjectsInOrgQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface TeamsListProjectsInOrgProps
	extends Omit<RequestInit, 'method' | 'body'>,
		TeamsListProjectsInOrgPathParams {
	queryParams: TeamsListProjectsInOrgQueryParams;
	paramsSerializer?: (params: TeamsListProjectsInOrgQueryParams) => string;
}

/**
 * Lists the organization projects for a team.
 *
 * **Note:** You can also specify a team by `org_id` and `team_id` using the route `GET /organizations/{org_id}/team/{team_id}/projects`.
 */
export async function teamsListProjectsInOrg(props: TeamsListProjectsInOrgProps) {
	const { org, team_slug, ...rest } = props;

	return _fetcher<unknown, TeamsListProjectsInOrgQueryParams, unknown>({
		path: `/orgs/${org}/teams/${team_slug}/projects`,
		method: 'GET',
		...rest,
	});
}
