/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface TeamsCheckPermissionsForRepoLegacyPathParams {
	team_id: number;
	owner: string;
	repo: string;
}

export interface TeamsCheckPermissionsForRepoLegacyProps
	extends Omit<RequestInit, 'method' | 'body'>,
		TeamsCheckPermissionsForRepoLegacyPathParams {}

/**
 * **Note**: Repositories inherited through a parent team will also be checked.
 *
 * **Deprecation Notice:** This endpoint route is deprecated and will be removed from the Teams API. We recommend migrating your existing code to use the new [Check team permissions for a repository](https://docs.github.com/rest/reference/teams#check-team-permissions-for-a-repository) endpoint.
 *
 * You can also get information about the specified repository, including what permissions the team grants on it, by passing the following custom [media type](https://docs.github.com/rest/overview/media-types/) via the `Accept` header:
 * @deprecated
 */
export async function teamsCheckPermissionsForRepoLegacy(
	props: TeamsCheckPermissionsForRepoLegacyProps,
) {
	const { team_id, owner, repo, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/teams/${team_id}/repos/${owner}/${repo}`,
		method: 'GET',
		...rest,
	});
}
