/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface TeamsListMembersInOrgQueryParams {
	role?: 'all' | 'maintainer' | 'member';
	per_page?: number;
	page?: number;
}

export interface TeamsListMembersInOrgPathParams {
	org: string;
	team_slug: string;
}

export interface TeamsListMembersInOrgProps
	extends Omit<RequestInit, 'method' | 'body'>,
		TeamsListMembersInOrgPathParams {
	queryParams: TeamsListMembersInOrgQueryParams;
}

export async function teamsListMembersInOrg(props: TeamsListMembersInOrgProps) {
	const { org, team_slug, queryParams, ...rest } = props;

	const response = await fetch(`/orgs/${org}/teams/${team_slug}/members`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
