/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

export interface TeamsListDiscussionCommentsInOrgPathParams {
	org: string;
	team_slug: string;
	discussion_number: number;
}

export interface TeamsListDiscussionCommentsInOrgQueryParams {
	/**
	 * @default "desc"
	 */
	direction?: 'asc' | 'desc';
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface TeamsListDiscussionCommentsInOrgProps
	extends Omit<RequestInit, 'method' | 'body'>,
		TeamsListDiscussionCommentsInOrgPathParams {
	queryParams: TeamsListDiscussionCommentsInOrgQueryParams;
}

/**
 * List all comments on a team discussion. OAuth access tokens require the `read:discussion` [scope](https://docs.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/).
 *
 * **Note:** You can also specify a team by `org_id` and `team_id` using the route `GET /organizations/{org_id}/team/{team_id}/discussions/{discussion_number}/comments`.
 */
export async function teamsListDiscussionCommentsInOrg(
	props: TeamsListDiscussionCommentsInOrgProps,
) {
	const { org, team_slug, discussion_number, queryParams, ...rest } = props;

	const response = await fetch(
		`/orgs/${org}/teams/${team_slug}/discussions/${discussion_number}/comments`,
		{
			method: 'GET',
			...rest,
			headers: {
				'Content-Type': 'application/json',
				...rest.headers,
			},
		},
	);

	const json = await response.json();

	return json;
}
