/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface TeamsGetDiscussionCommentLegacyPathParams {
	team_id: number;
	discussion_number: number;
	comment_number: number;
}

export interface TeamsGetDiscussionCommentLegacyProps
	extends Omit<RequestInit, 'method' | 'body'>,
		TeamsGetDiscussionCommentLegacyPathParams {}

/**
 * **Deprecation Notice:** This endpoint route is deprecated and will be removed from the Teams API. We recommend migrating your existing code to use the new [Get a discussion comment](https://docs.github.com/rest/reference/teams#get-a-discussion-comment) endpoint.
 *
 * Get a specific comment on a team discussion. OAuth access tokens require the `read:discussion` [scope](https://docs.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/).
 * @deprecated
 */
export async function teamsGetDiscussionCommentLegacy(props: TeamsGetDiscussionCommentLegacyProps) {
	const { team_id, discussion_number, comment_number, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/teams/${team_id}/discussions/${discussion_number}/comments/${comment_number}`,
		method: 'GET',
		...rest,
	});
}
