/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface TeamsListProjectsInOrgQueryParams {
	per_page?: number;
	page?: number;
}

export interface TeamsListProjectsInOrgPathParams {
	org: string;
	team_slug: string;
}

export interface TeamsListProjectsInOrgProps
	extends Omit<RequestInit, 'method' | 'body'>,
		TeamsListProjectsInOrgPathParams {
	queryParams: TeamsListProjectsInOrgQueryParams;
}

export async function teamsListProjectsInOrg(props: TeamsListProjectsInOrgProps) {
	const { org, team_slug, queryParams, ...rest } = props;

	const response = await fetch(`/orgs/${org}/teams/${team_slug}/projects`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
