/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface UsersListEmailsForAuthenticatedQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface UsersListEmailsForAuthenticatedProps extends Omit<RequestInit, 'method' | 'body'> {
	queryParams: UsersListEmailsForAuthenticatedQueryParams;
	paramsSerializer?: (params: UsersListEmailsForAuthenticatedQueryParams) => string;
}

/**
 * Lists all of your email addresses, and specifies which one is visible to the public. This endpoint is accessible with the `user:email` scope.
 */
export async function usersListEmailsForAuthenticated(props: UsersListEmailsForAuthenticatedProps) {
	const { ...rest } = props;

	return _fetcher<unknown, UsersListEmailsForAuthenticatedQueryParams, unknown>({
		path: `/user/emails`,
		method: 'GET',
		...rest,
	});
}
