/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface UsersGetByUsernamePathParams {
	username: string;
}

export interface UsersGetByUsernameProps
	extends Omit<RequestInit, 'method' | 'body'>,
		UsersGetByUsernamePathParams {}

export async function usersGetByUsername(props: UsersGetByUsernameProps) {
	const { username, ...rest } = props;

	const response = await fetch(`/users/${username}`, {
		method: 'GET',
		...rest,
	});

	const json = await response.json();

	return json;
}
