/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface UsersDeletePublicSshKeyForAuthenticatedPathParams {
	key_id: number;
}

export interface UsersDeletePublicSshKeyForAuthenticatedProps
	extends Omit<RequestInit, 'method' | 'body'>,
		UsersDeletePublicSshKeyForAuthenticatedPathParams {}

/**
 * Removes a public SSH key from the authenticated user's GitHub account. Requires that you are authenticated via Basic Auth or via OAuth with at least `admin:public_key` [scope](https://docs.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/).
 */
export async function usersDeletePublicSshKeyForAuthenticated(
	props: UsersDeletePublicSshKeyForAuthenticatedProps,
) {
	const { key_id, ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/user/keys/${key_id}`,
		method: 'DELETE',
		...rest,
	});
}
