/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface UsersListBlockedByAuthenticatedProps
	extends Omit<RequestInit, 'method' | 'body'> {}

/**
 * List the users you've blocked on your personal account.
 */
export async function usersListBlockedByAuthenticated(props: UsersListBlockedByAuthenticatedProps) {
	const { ...rest } = props;

	return _fetcher<unknown, unknown, unknown>({
		path: `/user/blocks`,
		method: 'GET',
		...rest,
	});
}
