/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

import { fetcher as _fetcher } from './fetcher';

export interface UsersListPublicEmailsForAuthenticatedQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface UsersListPublicEmailsForAuthenticatedProps
	extends Omit<RequestInit, 'method' | 'body'> {
	queryParams: UsersListPublicEmailsForAuthenticatedQueryParams;
	paramsSerializer?: (params: UsersListPublicEmailsForAuthenticatedQueryParams) => string;
}

/**
 * Lists your publicly visible email address, which you can set with the [Set primary email visibility for the authenticated user](https://docs.github.com/rest/reference/users#set-primary-email-visibility-for-the-authenticated-user) endpoint. This endpoint is accessible with the `user:email` scope.
 */
export async function usersListPublicEmailsForAuthenticated(
	props: UsersListPublicEmailsForAuthenticatedProps,
) {
	const { ...rest } = props;

	return _fetcher<unknown, UsersListPublicEmailsForAuthenticatedQueryParams, unknown>({
		path: `/user/public_emails`,
		method: 'GET',
		...rest,
	});
}
