/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
export interface UsersUpdateAuthenticatedProps extends Omit<RequestInit, 'method' | 'body'> {}

export async function usersUpdateAuthenticated(props: UsersUpdateAuthenticatedProps) {
	const { ...rest } = props;

	const response = await fetch(`/user`, {
		method: 'PATCH',
		...rest,
	});

	const json = await response.json();

	return json;
}
