/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseUpdatePetMutationProps {}

/**
 *
 */

export function useUpdatePetMutation(props: UseUpdatePetMutationProps) {
	return useMutation(() => Promise.resolve());
}
