/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

export interface FindPetsByStatusQueryParams {
	status: Array<'available' | 'pending' | 'sold'>;
}

export interface FindPetsByStatusProps extends Omit<RequestInit, 'method' | 'body'> {
	queryParams: FindPetsByStatusQueryParams;
}

/**
 * Multiple status values can be provided with comma separated strings
 */
export async function findPetsByStatus(props: FindPetsByStatusProps) {
	const { queryParams, ...rest } = props;

	const response = await fetch(`/pet/findByStatus`, {
		method: 'GET',
		...rest,
		headers: {
			'Content-Type': 'application/json',
			...rest.headers,
		},
	});

	const json = await response.json();

	return json;
}
