/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface ActivityListStargazersForRepoPathParams {
	owner: string;
	repo: string;
}

export interface ActivityListStargazersForRepoQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface UseActivityListStargazersForRepoQueryProps
	extends ActivityListStargazersForRepoPathParams {
	queryParams: ActivityListStargazersForRepoQueryParams;
}

/**
 * Lists the people that have starred the repository.
 *
 * You can also find out _when_ stars were created by passing the following custom [media type](https://docs.github.com/rest/overview/media-types/) via the `Accept` header:
 */

export function useActivityListStargazersForRepoQuery(
	props: UseActivityListStargazersForRepoQueryProps,
) {
	const { owner, repo, queryParams } = props;

	return useQuery(['activity/list-stargazers-for-repo', owner, repo, queryParams]);
}
