/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface ActionsGetGithubActionsPermissionsRepositoryPathParams {
	owner: string;
	repo: string;
}

export interface UseActionsGetGithubActionsPermissionsRepositoryQueryProps
	extends ActionsGetGithubActionsPermissionsRepositoryPathParams {}

/**
 * Gets the GitHub Actions permissions policy for a repository, including whether GitHub Actions is enabled and the actions allowed to run in the repository.
 *
 * You must authenticate using an access token with the `repo` scope to use this
 * endpoint. GitHub Apps must have the `administration` repository permission to use this API.
 */

export function useActionsGetGithubActionsPermissionsRepositoryQuery(
	props: UseActionsGetGithubActionsPermissionsRepositoryQueryProps,
) {
	const { owner, repo } = props;

	return useQuery(['actions/get-github-actions-permissions-repository', owner, repo]);
}
