/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

import type { AllowedActions } from '../schemas/AllowedActions';
import type { EnabledRepositories } from '../schemas/EnabledRepositories';

export interface UseActionsSetGithubActionsPermissionsOrganizationMutationPathParams {
	org: string;
}

export interface UseActionsSetGithubActionsPermissionsOrganizationMutationRequestBody {
	allowed_actions?: AllowedActions;
	enabled_repositories: EnabledRepositories;
}

export interface UseActionsSetGithubActionsPermissionsOrganizationMutationProps
	extends UseActionsSetGithubActionsPermissionsOrganizationMutationPathParams {
	body: UseActionsSetGithubActionsPermissionsOrganizationMutationRequestBody;
}

/**
 * Sets the GitHub Actions permissions policy for repositories and allowed actions in an organization.
 *
 * If the organization belongs to an enterprise that has set restrictive permissions at the enterprise level, such as `allowed_actions` to `selected` actions, then you cannot override them for the organization.
 *
 * You must authenticate using an access token with the `admin:org` scope to use this endpoint. GitHub Apps must have the `administration` organization permission to use this API.
 */

export function useActionsSetGithubActionsPermissionsOrganizationMutation(
	props: UseActionsSetGithubActionsPermissionsOrganizationMutationProps,
) {
	return useMutation(() => Promise.resolve());
}
