/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseActionsCreateRemoveTokenForRepoMutationPathParams {
	owner: string;
	repo: string;
}

export interface UseActionsCreateRemoveTokenForRepoMutationProps
	extends UseActionsCreateRemoveTokenForRepoMutationPathParams {}

/**
 * Returns a token that you can pass to remove a self-hosted runner from a repository. The token expires after one hour.
 * You must authenticate using an access token with the `repo` scope to use this endpoint.
 *
 * #### Example using remove token
 *
 * To remove your self-hosted runner from a repository, replace TOKEN with the remove token provided by this endpoint.
 *
 * ```
 * ./config.sh remove --token TOKEN
 * ```
 */

export function useActionsCreateRemoveTokenForRepoMutation(
	props: UseActionsCreateRemoveTokenForRepoMutationProps,
) {
	return useMutation(() => Promise.resolve());
}
