/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface UseActivityListReceivedEventsForUserQueryPathParams {
	username: string;
}

export interface UseActivityListReceivedEventsForUserQueryQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface UseActivityListReceivedEventsForUserQueryProps
	extends UseActivityListReceivedEventsForUserQueryPathParams {
	queryParams: UseActivityListReceivedEventsForUserQueryQueryParams;
}

/**
 * These are events that you've received by watching repos and following users. If you are authenticated as the given user, you will see private events. Otherwise, you'll only see public events.
 */

export function useActivityListReceivedEventsForUserQuery(
	props: UseActivityListReceivedEventsForUserQueryProps,
) {
	const { username, queryParams } = props;

	return useQuery(['activity/list-received-events-for-user', username, queryParams]);
}
