/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface UseActionsListSelfHostedRunnersForRepoQueryPathParams {
	owner: string;
	repo: string;
}

export interface UseActionsListSelfHostedRunnersForRepoQueryQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface UseActionsListSelfHostedRunnersForRepoQueryProps
	extends UseActionsListSelfHostedRunnersForRepoQueryPathParams {
	queryParams: UseActionsListSelfHostedRunnersForRepoQueryQueryParams;
}

/**
 * Lists all self-hosted runners configured in a repository. You must authenticate using an access token with the `repo` scope to use this endpoint.
 */

export function useActionsListSelfHostedRunnersForRepoQuery(
	props: UseActionsListSelfHostedRunnersForRepoQueryProps,
) {
	const { owner, repo, queryParams } = props;

	return useQuery(['actions/list-self-hosted-runners-for-repo', owner, repo, queryParams]);
}
