/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';
export interface AppsListInstallationsForAuthenticatedUserQueryParams {
	per_page?: number;
	page?: number;
}

export interface UseAppsListInstallationsForAuthenticatedUserQueryProps {
	queryParams: AppsListInstallationsForAuthenticatedUserQueryParams;
}

export function useAppsListInstallationsForAuthenticatedUserQuery(
	props: UseAppsListInstallationsForAuthenticatedUserQueryProps,
) {
	const { queryParams } = props;

	return useQuery(['apps/list-installations-for-authenticated-user', queryParams]);
}
