/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';
export interface ActionsListEnvironmentSecretsPathParams {
	repository_id: number;
	environment_name: string;
}

export interface ActionsListEnvironmentSecretsQueryParams {
	per_page?: number;
	page?: number;
}

export interface UseActionsListEnvironmentSecretsQueryProps
	extends ActionsListEnvironmentSecretsPathParams {
	queryParams: ActionsListEnvironmentSecretsQueryParams;
}

export function useActionsListEnvironmentSecretsQuery(
	props: UseActionsListEnvironmentSecretsQueryProps,
) {
	const { repository_id, environment_name, queryParams } = props;

	return useQuery([
		'actions/list-environment-secrets',
		repository_id,
		environment_name,
		queryParams,
	]);
}
