/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface UseActionsGetEnvironmentPublicKeyQueryPathParams {
	repository_id: number;
	environment_name: string;
}

export interface UseActionsGetEnvironmentPublicKeyQueryProps
	extends UseActionsGetEnvironmentPublicKeyQueryPathParams {}

/**
 * Get the public key for an environment, which you need to encrypt environment secrets. You need to encrypt a secret before you can create or update secrets. Anyone with read access to the repository can use this endpoint. If the repository is private you must use an access token with the `repo` scope. GitHub Apps must have the `secrets` repository permission to use this endpoint.
 */

export function useActionsGetEnvironmentPublicKeyQuery(
	props: UseActionsGetEnvironmentPublicKeyQueryProps,
) {
	const { repository_id, environment_name } = props;

	return useQuery(['actions/get-environment-public-key', repository_id, environment_name]);
}
