/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseAppsCreateFromManifestMutationPathParams {
	code: string;
}

export interface UseAppsCreateFromManifestMutationProps
	extends UseAppsCreateFromManifestMutationPathParams {}

/**
 * Use this endpoint to complete the handshake necessary when implementing the [GitHub App Manifest flow](https://docs.github.com/apps/building-github-apps/creating-github-apps-from-a-manifest/). When you create a GitHub App with the manifest flow, you receive a temporary `code` used to retrieve the GitHub App's `id`, `pem` (private key), and `webhook_secret`.
 */

export function useAppsCreateFromManifestMutation(props: UseAppsCreateFromManifestMutationProps) {
	return useMutation(() => Promise.resolve());
}
