/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';
export interface AppsListPlansStubbedQueryParams {
	per_page?: number;
	page?: number;
}

export interface UseAppsListPlansStubbedQueryProps {
	queryParams: AppsListPlansStubbedQueryParams;
}

export function useAppsListPlansStubbedQuery(props: UseAppsListPlansStubbedQueryProps) {
	const { queryParams } = props;

	return useQuery(['apps/list-plans-stubbed', queryParams]);
}
