/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';
export interface UseAppsGetAuthenticatedQueryProps {}

export function useAppsGetAuthenticatedQuery(props: UseAppsGetAuthenticatedQueryProps) {
	const {} = props;

	return useQuery(['apps/get-authenticated']);
}
