/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface ActionsGetRepoSecretPathParams {
	owner: string;
	repo: string;
	secret_name: string;
}

export interface UseActionsGetRepoSecretQueryProps extends ActionsGetRepoSecretPathParams {}

/**
 * Gets a single repository secret without revealing its encrypted value. You must authenticate using an access token with the `repo` scope to use this endpoint. GitHub Apps must have the `secrets` repository permission to use this endpoint.
 */

export function useActionsGetRepoSecretQuery(props: UseActionsGetRepoSecretQueryProps) {
	const { owner, repo, secret_name } = props;

	return useQuery(['actions/get-repo-secret', owner, repo, secret_name]);
}
