/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseActionsDeleteEnvironmentSecretMutationPathParams {
	repository_id: number;
	environment_name: string;
	secret_name: string;
}

export interface UseActionsDeleteEnvironmentSecretMutationProps
	extends UseActionsDeleteEnvironmentSecretMutationPathParams {}

/**
 * Deletes a secret in an environment using the secret name. You must authenticate using an access token with the `repo` scope to use this endpoint. GitHub Apps must have the `secrets` repository permission to use this endpoint.
 */

export function useActionsDeleteEnvironmentSecretMutation(
	props: UseActionsDeleteEnvironmentSecretMutationProps,
) {
	return useMutation(() => Promise.resolve());
}
