/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseActionsSetSelectedReposForOrgSecretMutationPathParams {
	org: string;
	secret_name: string;
}

export interface UseActionsSetSelectedReposForOrgSecretMutationRequestBody {
	/**
	 * An array of repository ids that can access the organization secret. You can only provide a list of repository ids when the `visibility` is set to `selected`. You can add and remove individual repositories using the [Set selected repositories for an organization secret](https://docs.github.com/rest/reference/actions#set-selected-repositories-for-an-organization-secret) and [Remove selected repository from an organization secret](https://docs.github.com/rest/reference/actions#remove-selected-repository-from-an-organization-secret) endpoints.
	 */
	selected_repository_ids?: number[];
}

export interface UseActionsSetSelectedReposForOrgSecretMutationProps
	extends UseActionsSetSelectedReposForOrgSecretMutationPathParams {
	body: UseActionsSetSelectedReposForOrgSecretMutationRequestBody;
}

/**
 * Replaces all repositories for an organization secret when the `visibility` for repository access is set to `selected`. The visibility is set when you [Create or update an organization secret](https://docs.github.com/rest/reference/actions#create-or-update-an-organization-secret). You must authenticate using an access token with the `admin:org` scope to use this endpoint. GitHub Apps must have the `secrets` organization permission to use this endpoint.
 */

export function useActionsSetSelectedReposForOrgSecretMutation(
	props: UseActionsSetSelectedReposForOrgSecretMutationProps,
) {
	return useMutation(() => Promise.resolve());
}
