/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseAppsDeleteTokenMutationPathParams {
	client_id: string;
}

export interface UseAppsDeleteTokenMutationProps extends UseAppsDeleteTokenMutationPathParams {}

/**
 * OAuth application owners can revoke a single token for an OAuth application. You must use [Basic Authentication](https://docs.github.com/rest/overview/other-authentication-methods#basic-authentication) when accessing this endpoint, using the OAuth application's `client_id` and `client_secret` as the username and password.
 */

export function useAppsDeleteTokenMutation(props: UseAppsDeleteTokenMutationProps) {
	return useMutation(() => Promise.resolve());
}
