/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface ActivityListWatchersForRepoPathParams {
	owner: string;
	repo: string;
}

export interface ActivityListWatchersForRepoQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface UseActivityListWatchersForRepoQueryProps
	extends ActivityListWatchersForRepoPathParams {
	queryParams: ActivityListWatchersForRepoQueryParams;
}

/**
 * Lists the people watching the specified repository.
 */

export function useActivityListWatchersForRepoQuery(
	props: UseActivityListWatchersForRepoQueryProps,
) {
	const { owner, repo, queryParams } = props;

	return useQuery(['activity/list-watchers-for-repo', owner, repo, queryParams]);
}
