/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface UseActionsListRepoWorkflowsQueryPathParams {
	owner: string;
	repo: string;
}

export interface UseActionsListRepoWorkflowsQueryQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface UseActionsListRepoWorkflowsQueryProps
	extends UseActionsListRepoWorkflowsQueryPathParams {
	queryParams: UseActionsListRepoWorkflowsQueryQueryParams;
}

/**
 * Lists the workflows in a repository. Anyone with read access to the repository can use this endpoint. If the repository is private you must use an access token with the `repo` scope. GitHub Apps must have the `actions:read` permission to use this endpoint.
 */

export function useActionsListRepoWorkflowsQuery(props: UseActionsListRepoWorkflowsQueryProps) {
	const { owner, repo, queryParams } = props;

	return useQuery(['actions/list-repo-workflows', owner, repo, queryParams]);
}
