/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface BillingGetGithubPackagesBillingOrgPathParams {
	org: string;
}

export interface UseBillingGetGithubPackagesBillingOrgQueryProps
	extends BillingGetGithubPackagesBillingOrgPathParams {}

/**
 * Gets the free and paid storage usued for GitHub Packages in gigabytes.
 *
 * Paid minutes only apply to packages stored for private repositories. For more information, see "[Managing billing for GitHub Packages](https://help.github.com/github/setting-up-and-managing-billing-and-payments-on-github/managing-billing-for-github-packages)."
 *
 * Access tokens must have the `repo` or `admin:org` scope.
 */

export function useBillingGetGithubPackagesBillingOrgQuery(
	props: UseBillingGetGithubPackagesBillingOrgQueryProps,
) {
	const { org } = props;

	return useQuery(['billing/get-github-packages-billing-org', org]);
}
