/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';
export interface EnterpriseAdminListSelfHostedRunnerGroupsForEnterprisePathParams {
	enterprise: string;
}

export interface EnterpriseAdminListSelfHostedRunnerGroupsForEnterpriseQueryParams {
	per_page?: number;
	page?: number;
}

export interface UseEnterpriseAdminListSelfHostedRunnerGroupsForEnterpriseQueryProps
	extends EnterpriseAdminListSelfHostedRunnerGroupsForEnterprisePathParams {
	queryParams: EnterpriseAdminListSelfHostedRunnerGroupsForEnterpriseQueryParams;
}

export function useEnterpriseAdminListSelfHostedRunnerGroupsForEnterpriseQuery(
	props: UseEnterpriseAdminListSelfHostedRunnerGroupsForEnterpriseQueryProps,
) {
	const { enterprise, queryParams } = props;

	return useQuery([
		'enterprise-admin/list-self-hosted-runner-groups-for-enterprise',
		enterprise,
		queryParams,
	]);
}
