/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface EnterpriseAdminListRunnerApplicationsForEnterprisePathParams {
	enterprise: string;
}

export interface UseEnterpriseAdminListRunnerApplicationsForEnterpriseQueryProps
	extends EnterpriseAdminListRunnerApplicationsForEnterprisePathParams {}

/**
 * Lists binaries for the runner application that you can download and run.
 *
 * You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */

export function useEnterpriseAdminListRunnerApplicationsForEnterpriseQuery(
	props: UseEnterpriseAdminListRunnerApplicationsForEnterpriseQueryProps,
) {
	const { enterprise } = props;

	return useQuery(['enterprise-admin/list-runner-applications-for-enterprise', enterprise]);
}
