/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseEnterpriseAdminCreateRegistrationTokenForEnterpriseMutationPathParams {
	enterprise: string;
}

export interface UseEnterpriseAdminCreateRegistrationTokenForEnterpriseMutationProps
	extends UseEnterpriseAdminCreateRegistrationTokenForEnterpriseMutationPathParams {}

/**
 * Returns a token that you can pass to the `config` script. The token expires after one hour.
 *
 * You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 *
 * #### Example using registration token
 *
 * Configure your self-hosted runner, replacing `TOKEN` with the registration token provided by this endpoint.
 *
 * ```
 * ./config.sh --url https://github.com/enterprises/octo-enterprise --token TOKEN
 * ```
 */

export function useEnterpriseAdminCreateRegistrationTokenForEnterpriseMutation(
	props: UseEnterpriseAdminCreateRegistrationTokenForEnterpriseMutationProps,
) {
	return useMutation(() => Promise.resolve());
}
