/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export function useEnterpriseAdminUpdateAttributeForEnterpriseGroupMutation() {
	return useMutation();
}
