/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseEnterpriseAdminSetInformationForProvisionedEnterpriseGroupMutationPathParams {
	enterprise: string;
	scim_group_id: string;
}

export interface UseEnterpriseAdminSetInformationForProvisionedEnterpriseGroupMutationRequestBody {
	/**
	 * The name of the SCIM group. This must match the GitHub organization that the group maps to.
	 */
	displayName: string;
	members?: Array<{
		/**
		 * The SCIM user ID for a user.
		 */
		value: string;
	}>;
	/**
	 * The SCIM schema URIs.
	 */
	schemas: string[];
}

export interface UseEnterpriseAdminSetInformationForProvisionedEnterpriseGroupMutationProps
	extends UseEnterpriseAdminSetInformationForProvisionedEnterpriseGroupMutationPathParams {
	body: UseEnterpriseAdminSetInformationForProvisionedEnterpriseGroupMutationRequestBody;
}

/**
 * **Note:** The SCIM API endpoints for enterprise accounts are currently in beta and are subject to change.
 *
 * Replaces an existing provisioned group’s information. You must provide all the information required for the group as if you were provisioning it for the first time. Any existing group information that you don't provide will be removed, including group membership. If you want to only update a specific attribute, use the [Update an attribute for a SCIM enterprise group](#update-an-attribute-for-a-scim-enterprise-group) endpoint instead.
 */

export function useEnterpriseAdminSetInformationForProvisionedEnterpriseGroupMutation(
	props: UseEnterpriseAdminSetInformationForProvisionedEnterpriseGroupMutationProps,
) {
	return useMutation(() => Promise.resolve());
}
