/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface UseGitignoreGetTemplateQueryPathParams {
	name: string;
}

export interface UseGitignoreGetTemplateQueryProps extends UseGitignoreGetTemplateQueryPathParams {}

/**
 * The API also allows fetching the source of a single template.
 * Use the raw [media type](https://docs.github.com/rest/overview/media-types/) to get the raw contents.
 */

export function useGitignoreGetTemplateQuery(props: UseGitignoreGetTemplateQueryProps) {
	const { name } = props;

	return useQuery(['gitignore/get-template', name]);
}
