/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseGistsUpdateCommentMutationPathParams {
	gist_id: string;
	comment_id: number;
}

export interface UseGistsUpdateCommentMutationRequestBody {
	/**
	 * The comment text.
	 * @example "Body of the attachment"
	 */
	body: string;
}

export interface UseGistsUpdateCommentMutationProps
	extends UseGistsUpdateCommentMutationPathParams {
	body: UseGistsUpdateCommentMutationRequestBody;
}

/**
 *
 */

export function useGistsUpdateCommentMutation(props: UseGistsUpdateCommentMutationProps) {
	return useMutation(() => Promise.resolve());
}
