/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseGistsCreateCommentMutationPathParams {
	gist_id: string;
}

export interface UseGistsCreateCommentMutationRequestBody {
	/**
	 * The comment text.
	 * @example "Body of the attachment"
	 */
	body: string;
}

export interface UseGistsCreateCommentMutationProps
	extends UseGistsCreateCommentMutationPathParams {
	body: UseGistsCreateCommentMutationRequestBody;
}

/**
 *
 */

export function useGistsCreateCommentMutation(props: UseGistsCreateCommentMutationProps) {
	return useMutation(() => Promise.resolve());
}
