/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';
export interface GistsListForUserPathParams {
	username: string;
}

export interface GistsListForUserQueryParams {
	since?: string;
	per_page?: number;
	page?: number;
}

export interface UseGistsListForUserQueryProps extends GistsListForUserPathParams {
	queryParams: GistsListForUserQueryParams;
}

export function useGistsListForUserQuery(props: UseGistsListForUserQueryProps) {
	const { username, queryParams } = props;

	return useQuery(['gists/list-for-user', username, queryParams]);
}
