/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseInteractionsRemoveRestrictionsForRepoMutationPathParams {
	owner: string;
	repo: string;
}

export interface UseInteractionsRemoveRestrictionsForRepoMutationProps
	extends UseInteractionsRemoveRestrictionsForRepoMutationPathParams {}

/**
 * Removes all interaction restrictions from the given repository. You must have owner or admin access to remove restrictions. If the interaction limit is set for the user or organization that owns this repository, you will receive a `409 Conflict` response and will not be able to use this endpoint to change the interaction limit for a single repository.
 */

export function useInteractionsRemoveRestrictionsForRepoMutation(
	props: UseInteractionsRemoveRestrictionsForRepoMutationProps,
) {
	return useMutation(() => Promise.resolve());
}
