/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseIssuesSetLabelsMutationPathParams {
	owner: string;
	repo: string;
	issue_number: number;
}

export interface UseIssuesSetLabelsMutationRequestBody {
	/**
	 * The names of the labels to add to the issue. You can pass an empty array to remove all labels. **Note:** Alternatively, you can pass a single label as a `string` or an `array` of labels directly, but GitHub recommends passing an object with the `labels` key.
	 */
	labels?: string[];
}

export interface UseIssuesSetLabelsMutationProps extends UseIssuesSetLabelsMutationPathParams {
	body: UseIssuesSetLabelsMutationRequestBody;
}

/**
 * Removes any previous labels and sets the new labels for an issue.
 */

export function useIssuesSetLabelsMutation(props: UseIssuesSetLabelsMutationProps) {
	return useMutation(() => Promise.resolve());
}
