/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface UseIssuesListLabelsForMilestoneQueryPathParams {
	owner: string;
	repo: string;
	milestone_number: number;
}

export interface UseIssuesListLabelsForMilestoneQueryQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface UseIssuesListLabelsForMilestoneQueryProps
	extends UseIssuesListLabelsForMilestoneQueryPathParams {
	queryParams: UseIssuesListLabelsForMilestoneQueryQueryParams;
}

/**
 *
 */

export function useIssuesListLabelsForMilestoneQuery(
	props: UseIssuesListLabelsForMilestoneQueryProps,
) {
	const { owner, repo, milestone_number, queryParams } = props;

	return useQuery(['issues/list-labels-for-milestone', owner, repo, milestone_number, queryParams]);
}
