/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';
export interface IssuesListCommentsPathParams {
	owner: string;
	repo: string;
	issue_number: number;
}

export interface IssuesListCommentsQueryParams {
	since?: string;
	per_page?: number;
	page?: number;
}

export interface UseIssuesListCommentsQueryProps extends IssuesListCommentsPathParams {
	queryParams: IssuesListCommentsQueryParams;
}

export function useIssuesListCommentsQuery(props: UseIssuesListCommentsQueryProps) {
	const { owner, repo, issue_number, queryParams } = props;

	return useQuery(['issues/list-comments', owner, repo, issue_number, queryParams]);
}
