/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface UseIssuesListLabelsForRepoQueryPathParams {
	owner: string;
	repo: string;
}

export interface UseIssuesListLabelsForRepoQueryQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface UseIssuesListLabelsForRepoQueryProps
	extends UseIssuesListLabelsForRepoQueryPathParams {
	queryParams: UseIssuesListLabelsForRepoQueryQueryParams;
}

/**
 *
 */

export function useIssuesListLabelsForRepoQuery(props: UseIssuesListLabelsForRepoQueryProps) {
	const { owner, repo, queryParams } = props;

	return useQuery(['issues/list-labels-for-repo', owner, repo, queryParams]);
}
