/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';
export interface IssuesListAssigneesPathParams {
	owner: string;
	repo: string;
}

export interface IssuesListAssigneesQueryParams {
	per_page?: number;
	page?: number;
}

export interface UseIssuesListAssigneesQueryProps extends IssuesListAssigneesPathParams {
	queryParams: IssuesListAssigneesQueryParams;
}

export function useIssuesListAssigneesQuery(props: UseIssuesListAssigneesQueryProps) {
	const { owner, repo, queryParams } = props;

	return useQuery(['issues/list-assignees', owner, repo, queryParams]);
}
