/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';
export interface LicensesGetPathParams {
	license: string;
}

export interface UseLicensesGetQueryProps extends LicensesGetPathParams {}

export function useLicensesGetQuery(props: UseLicensesGetQueryProps) {
	const { license } = props;

	return useQuery(['licenses/get', license]);
}
