/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface UseLicensesGetForRepoQueryPathParams {
	owner: string;
	repo: string;
}

export interface UseLicensesGetForRepoQueryProps extends UseLicensesGetForRepoQueryPathParams {}

/**
 * This method returns the contents of the repository's license file, if one is detected.
 *
 * Similar to [Get repository content](https://docs.github.com/rest/reference/repos#get-repository-content), this method also supports [custom media types](https://docs.github.com/rest/overview/media-types) for retrieving the raw license content or rendered license HTML.
 */

export function useLicensesGetForRepoQuery(props: UseLicensesGetForRepoQueryProps) {
	const { owner, repo } = props;

	return useQuery(['licenses/get-for-repo', owner, repo]);
}
