/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';
export interface MigrationsListForAuthenticatedUserQueryParams {
	per_page?: number;
	page?: number;
}

export interface UseMigrationsListForAuthenticatedUserQueryProps {
	queryParams: MigrationsListForAuthenticatedUserQueryParams;
}

export function useMigrationsListForAuthenticatedUserQuery(
	props: UseMigrationsListForAuthenticatedUserQueryProps,
) {
	const { queryParams } = props;

	return useQuery(['migrations/list-for-authenticated-user', queryParams]);
}
