/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';
export interface UseMetaRootQueryProps {}

export function useMetaRootQuery(props: UseMetaRootQueryProps) {
	const {} = props;

	return useQuery(['meta/root']);
}
