/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface UseMigrationsListForOrgQueryPathParams {
	org: string;
}

export interface UseMigrationsListForOrgQueryQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
	exclude?: Array<'repositories'>;
}

export interface UseMigrationsListForOrgQueryProps extends UseMigrationsListForOrgQueryPathParams {
	queryParams: UseMigrationsListForOrgQueryQueryParams;
}

/**
 * Lists the most recent migrations.
 */

export function useMigrationsListForOrgQuery(props: UseMigrationsListForOrgQueryProps) {
	const { org, queryParams } = props;

	return useQuery(['migrations/list-for-org', org, queryParams]);
}
