/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface UseMetaGetOctocatQueryQueryParams {
	s?: string;
}

export interface UseMetaGetOctocatQueryProps {
	queryParams: UseMetaGetOctocatQueryQueryParams;
}

/**
 * Get the octocat as ASCII art
 */

export function useMetaGetOctocatQuery(props: UseMetaGetOctocatQueryProps) {
	const { queryParams } = props;

	return useQuery(['meta/get-octocat', queryParams]);
}
