/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseMigrationsStartImportMutationPathParams {
	owner: string;
	repo: string;
}

export interface UseMigrationsStartImportMutationRequestBody {
	/**
	 * For a tfvc import, the name of the project that is being imported.
	 */
	tfvc_project?: string;
	/**
	 * The originating VCS type. Can be one of `subversion`, `git`, `mercurial`, or `tfvc`. Please be aware that without this parameter, the import job will take additional time to detect the VCS type before beginning the import. This detection step will be reflected in the response.
	 */
	vcs?: 'git' | 'mercurial' | 'subversion' | 'tfvc';
	/**
	 * If authentication is required, the password to provide to `vcs_url`.
	 */
	vcs_password?: string;
	/**
	 * The URL of the originating repository.
	 */
	vcs_url: string;
	/**
	 * If authentication is required, the username to provide to `vcs_url`.
	 */
	vcs_username?: string;
}

export interface UseMigrationsStartImportMutationProps
	extends UseMigrationsStartImportMutationPathParams {
	body: UseMigrationsStartImportMutationRequestBody;
}

/**
 * Start a source import to a GitHub repository using GitHub Importer.
 */

export function useMigrationsStartImportMutation(props: UseMigrationsStartImportMutationProps) {
	return useMutation(() => Promise.resolve());
}
