/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseMigrationsUnlockRepoForAuthenticatedUserMutationPathParams {
	migration_id: number;
	repo_name: string;
}

export interface UseMigrationsUnlockRepoForAuthenticatedUserMutationProps
	extends UseMigrationsUnlockRepoForAuthenticatedUserMutationPathParams {}

/**
 * Unlocks a repository. You can lock repositories when you [start a user migration](https://docs.github.com/rest/reference/migrations#start-a-user-migration). Once the migration is complete you can unlock each repository to begin using it again or [delete the repository](https://docs.github.com/rest/reference/repos#delete-a-repository) if you no longer need the source data. Returns a status of `404 Not Found` if the repository is not locked.
 */

export function useMigrationsUnlockRepoForAuthenticatedUserMutation(
	props: UseMigrationsUnlockRepoForAuthenticatedUserMutationProps,
) {
	return useMutation(() => Promise.resolve());
}
