/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseOrgsUpdateMembershipForAuthenticatedUserMutationPathParams {
	org: string;
}

export interface UseOrgsUpdateMembershipForAuthenticatedUserMutationRequestBody {
	/**
	 * The state that the membership should be in. Only `"active"` will be accepted.
	 */
	state: 'active';
}

export interface UseOrgsUpdateMembershipForAuthenticatedUserMutationProps
	extends UseOrgsUpdateMembershipForAuthenticatedUserMutationPathParams {
	body: UseOrgsUpdateMembershipForAuthenticatedUserMutationRequestBody;
}

/**
 *
 */

export function useOrgsUpdateMembershipForAuthenticatedUserMutation(
	props: UseOrgsUpdateMembershipForAuthenticatedUserMutationProps,
) {
	return useMutation(() => Promise.resolve());
}
