/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';
export interface OrgsListQueryParams {
	since?: number;
	per_page?: number;
}

export interface UseOrgsListQueryProps {
	queryParams: OrgsListQueryParams;
}

export function useOrgsListQuery(props: UseOrgsListQueryProps) {
	const { queryParams } = props;

	return useQuery(['orgs/list', queryParams]);
}
