/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseOrgsPingWebhookMutationPathParams {
	org: string;
	hook_id: number;
}

export interface UseOrgsPingWebhookMutationProps extends UseOrgsPingWebhookMutationPathParams {}

/**
 * This will trigger a [ping event](https://docs.github.com/webhooks/#ping-event) to be sent to the hook.
 */

export function useOrgsPingWebhookMutation(props: UseOrgsPingWebhookMutationProps) {
	return useMutation(() => Promise.resolve());
}
