/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';
export interface OauthAuthorizationsListGrantsQueryParams {
	per_page?: number;
	page?: number;
	client_id?: string;
}

export interface UseOauthAuthorizationsListGrantsQueryProps {
	queryParams: OauthAuthorizationsListGrantsQueryParams;
}

export function useOauthAuthorizationsListGrantsQuery(
	props: UseOauthAuthorizationsListGrantsQueryProps,
) {
	const { queryParams } = props;

	return useQuery(['oauth-authorizations/list-grants', queryParams]);
}
