/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseOrgsRemoveOutsideCollaboratorMutationPathParams {
	org: string;
	username: string;
}

export interface UseOrgsRemoveOutsideCollaboratorMutationProps
	extends UseOrgsRemoveOutsideCollaboratorMutationPathParams {}

/**
 * Removing a user from this list will remove them from all the organization's repositories.
 */

export function useOrgsRemoveOutsideCollaboratorMutation(
	props: UseOrgsRemoveOutsideCollaboratorMutationProps,
) {
	return useMutation(() => Promise.resolve());
}
