/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface UseOrgsListMembersQueryPathParams {
	org: string;
}

export interface UseOrgsListMembersQueryQueryParams {
	/**
	 * @default "all"
	 */
	filter?: '2fa_disabled' | 'all';
	/**
	 * @default "all"
	 */
	role?: 'admin' | 'all' | 'member';
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface UseOrgsListMembersQueryProps extends UseOrgsListMembersQueryPathParams {
	queryParams: UseOrgsListMembersQueryQueryParams;
}

/**
 * List all users who are members of an organization. If the authenticated user is also a member of this organization then both concealed and public members will be returned.
 */

export function useOrgsListMembersQuery(props: UseOrgsListMembersQueryProps) {
	const { org, queryParams } = props;

	return useQuery(['orgs/list-members', org, queryParams]);
}
