/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseOrgsRemoveMembershipForUserMutationPathParams {
	org: string;
	username: string;
}

export interface UseOrgsRemoveMembershipForUserMutationProps
	extends UseOrgsRemoveMembershipForUserMutationPathParams {}

/**
 * In order to remove a user's membership with an organization, the authenticated user must be an organization owner.
 *
 * If the specified user is an active member of the organization, this will remove them from the organization. If the specified user has been invited to the organization, this will cancel their invitation. The specified user will receive an email notification in both cases.
 */

export function useOrgsRemoveMembershipForUserMutation(
	props: UseOrgsRemoveMembershipForUserMutationProps,
) {
	return useMutation(() => Promise.resolve());
}
