/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';
export interface OrgsListAppInstallationsPathParams {
	org: string;
}

export interface OrgsListAppInstallationsQueryParams {
	per_page?: number;
	page?: number;
}

export interface UseOrgsListAppInstallationsQueryProps extends OrgsListAppInstallationsPathParams {
	queryParams: OrgsListAppInstallationsQueryParams;
}

export function useOrgsListAppInstallationsQuery(props: UseOrgsListAppInstallationsQueryProps) {
	const { org, queryParams } = props;

	return useQuery(['orgs/list-app-installations', org, queryParams]);
}
