/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface UseOrgsListWebhooksQueryPathParams {
	org: string;
}

export interface UseOrgsListWebhooksQueryQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface UseOrgsListWebhooksQueryProps extends UseOrgsListWebhooksQueryPathParams {
	queryParams: UseOrgsListWebhooksQueryQueryParams;
}

/**
 *
 */

export function useOrgsListWebhooksQuery(props: UseOrgsListWebhooksQueryProps) {
	const { org, queryParams } = props;

	return useQuery(['orgs/list-webhooks', org, queryParams]);
}
