/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseOrgsRemovePublicMembershipForAuthenticatedUserMutationPathParams {
	org: string;
	username: string;
}

export interface UseOrgsRemovePublicMembershipForAuthenticatedUserMutationProps
	extends UseOrgsRemovePublicMembershipForAuthenticatedUserMutationPathParams {}

/**
 *
 */

export function useOrgsRemovePublicMembershipForAuthenticatedUserMutation(
	props: UseOrgsRemovePublicMembershipForAuthenticatedUserMutationProps,
) {
	return useMutation(() => Promise.resolve());
}
