/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseOrgsCancelInvitationMutationPathParams {
	org: string;
	invitation_id: number;
}

export interface UseOrgsCancelInvitationMutationProps
	extends UseOrgsCancelInvitationMutationPathParams {}

/**
 * Cancel an organization invitation. In order to cancel an organization invitation, the authenticated user must be an organization owner.
 *
 * This endpoint triggers [notifications](https://docs.github.com/en/github/managing-subscriptions-and-notifications-on-github/about-notifications).
 */

export function useOrgsCancelInvitationMutation(props: UseOrgsCancelInvitationMutationProps) {
	return useMutation(() => Promise.resolve());
}
