/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';
export interface ProjectsListForRepoPathParams {
	owner: string;
	repo: string;
}

export interface ProjectsListForRepoQueryParams {
	state?: 'all' | 'closed' | 'open';
	per_page?: number;
	page?: number;
}

export interface UseProjectsListForRepoQueryProps extends ProjectsListForRepoPathParams {
	queryParams: ProjectsListForRepoQueryParams;
}

export function useProjectsListForRepoQuery(props: UseProjectsListForRepoQueryProps) {
	const { owner, repo, queryParams } = props;

	return useQuery(['projects/list-for-repo', owner, repo, queryParams]);
}
