/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';
export interface PullsListCommentsForReviewPathParams {
	owner: string;
	repo: string;
	pull_number: number;
	review_id: number;
}

export interface PullsListCommentsForReviewQueryParams {
	per_page?: number;
	page?: number;
}

export interface UsePullsListCommentsForReviewQueryProps
	extends PullsListCommentsForReviewPathParams {
	queryParams: PullsListCommentsForReviewQueryParams;
}

export function usePullsListCommentsForReviewQuery(props: UsePullsListCommentsForReviewQueryProps) {
	const { owner, repo, pull_number, review_id, queryParams } = props;

	return useQuery([
		'pulls/list-comments-for-review',
		owner,
		repo,
		pull_number,
		review_id,
		queryParams,
	]);
}
