/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseProjectsDeleteCardMutationPathParams {
	card_id: number;
}

export interface UseProjectsDeleteCardMutationProps
	extends UseProjectsDeleteCardMutationPathParams {}

/**
 *
 */

export function useProjectsDeleteCardMutation(props: UseProjectsDeleteCardMutationProps) {
	return useMutation(() => Promise.resolve());
}
