/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface UsePackagesGetPackageVersionForAuthenticatedUserQueryPathParams {
	package_type: 'container' | 'docker' | 'maven' | 'npm' | 'nuget' | 'rubygems';
	package_name: string;
	package_version_id: number;
}

export interface UsePackagesGetPackageVersionForAuthenticatedUserQueryProps
	extends UsePackagesGetPackageVersionForAuthenticatedUserQueryPathParams {}

/**
 * Gets a specific package version for a package owned by the authenticated user.
 *
 * To use this endpoint, you must authenticate using an access token with the `packages:read` scope.
 * If `package_type` is not `container`, your token must also include the `repo` scope.
 */

export function usePackagesGetPackageVersionForAuthenticatedUserQuery(
	props: UsePackagesGetPackageVersionForAuthenticatedUserQueryProps,
) {
	const { package_type, package_name, package_version_id } = props;

	return useQuery([
		'packages/get-package-version-for-authenticated-user',
		package_type,
		package_name,
		package_version_id,
	]);
}
