/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface UsePullsListCommitsQueryPathParams {
	owner: string;
	repo: string;
	pull_number: number;
}

export interface UsePullsListCommitsQueryQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface UsePullsListCommitsQueryProps extends UsePullsListCommitsQueryPathParams {
	queryParams: UsePullsListCommitsQueryQueryParams;
}

/**
 * Lists a maximum of 250 commits for a pull request. To receive a complete commit list for pull requests with more than 250 commits, use the [List commits](https://docs.github.com/rest/reference/repos#list-commits) endpoint.
 */

export function usePullsListCommitsQuery(props: UsePullsListCommitsQueryProps) {
	const { owner, repo, pull_number, queryParams } = props;

	return useQuery(['pulls/list-commits', owner, repo, pull_number, queryParams]);
}
