/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface ReposListCollaboratorsPathParams {
	owner: string;
	repo: string;
}

export interface ReposListCollaboratorsQueryParams {
	/**
	 * @default "all"
	 */
	affiliation?: 'all' | 'direct' | 'outside';
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface UseReposListCollaboratorsQueryProps extends ReposListCollaboratorsPathParams {
	queryParams: ReposListCollaboratorsQueryParams;
}

/**
 * For organization-owned repositories, the list of collaborators includes outside collaborators, organization members that are direct collaborators, organization members with access through team memberships, organization members with access through default organization permissions, and organization owners.
 *
 * Team members will include the members of child teams.
 */

export function useReposListCollaboratorsQuery(props: UseReposListCollaboratorsQueryProps) {
	const { owner, repo, queryParams } = props;

	return useQuery(['repos/list-collaborators', owner, repo, queryParams]);
}
