/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';
export interface UseRateLimitGetQueryProps {}

export function useRateLimitGetQuery(props: UseRateLimitGetQueryProps) {
	const {} = props;

	return useQuery(['rate-limit/get']);
}
