/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface ReposGetReleasePathParams {
	owner: string;
	repo: string;
	release_id: number;
}

export interface UseReposGetReleaseQueryProps extends ReposGetReleasePathParams {}

/**
 * **Note:** This returns an `upload_url` key corresponding to the endpoint for uploading release assets. This key is a [hypermedia resource](https://docs.github.com/rest/overview/resources-in-the-rest-api#hypermedia).
 */

export function useReposGetReleaseQuery(props: UseReposGetReleaseQueryProps) {
	const { owner, repo, release_id } = props;

	return useQuery(['repos/get-release', owner, repo, release_id]);
}
