/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface ReactionsListForTeamDiscussionCommentInOrgPathParams {
	org: string;
	team_slug: string;
	discussion_number: number;
	comment_number: number;
}

export interface ReactionsListForTeamDiscussionCommentInOrgQueryParams {
	content?: '+1' | '-1' | 'confused' | 'eyes' | 'heart' | 'hooray' | 'laugh' | 'rocket';
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface UseReactionsListForTeamDiscussionCommentInOrgQueryProps
	extends ReactionsListForTeamDiscussionCommentInOrgPathParams {
	queryParams: ReactionsListForTeamDiscussionCommentInOrgQueryParams;
}

/**
 * List the reactions to a [team discussion comment](https://docs.github.com/rest/reference/teams#discussion-comments/). OAuth access tokens require the `read:discussion` [scope](https://docs.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/).
 *
 * **Note:** You can also specify a team by `org_id` and `team_id` using the route `GET /organizations/:org_id/team/:team_id/discussions/:discussion_number/comments/:comment_number/reactions`.
 */

export function useReactionsListForTeamDiscussionCommentInOrgQuery(
	props: UseReactionsListForTeamDiscussionCommentInOrgQueryProps,
) {
	const { org, team_slug, discussion_number, comment_number, queryParams } = props;

	return useQuery([
		'reactions/list-for-team-discussion-comment-in-org',
		org,
		team_slug,
		discussion_number,
		comment_number,
		queryParams,
	]);
}
