/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';
export interface ReposListReleaseAssetsPathParams {
	owner: string;
	repo: string;
	release_id: number;
}

export interface ReposListReleaseAssetsQueryParams {
	per_page?: number;
	page?: number;
}

export interface UseReposListReleaseAssetsQueryProps extends ReposListReleaseAssetsPathParams {
	queryParams: ReposListReleaseAssetsQueryParams;
}

export function useReposListReleaseAssetsQuery(props: UseReposListReleaseAssetsQueryProps) {
	const { owner, repo, release_id, queryParams } = props;

	return useQuery(['repos/list-release-assets', owner, repo, release_id, queryParams]);
}
