/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';
export interface ReposGetContributorsStatsPathParams {
	owner: string;
	repo: string;
}

export interface UseReposGetContributorsStatsQueryProps
	extends ReposGetContributorsStatsPathParams {}

export function useReposGetContributorsStatsQuery(props: UseReposGetContributorsStatsQueryProps) {
	const { owner, repo } = props;

	return useQuery(['repos/get-contributors-stats', owner, repo]);
}
