/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface UseReposListPullRequestsAssociatedWithCommitQueryPathParams {
	owner: string;
	repo: string;
	commit_sha: string;
}

export interface UseReposListPullRequestsAssociatedWithCommitQueryQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface UseReposListPullRequestsAssociatedWithCommitQueryProps
	extends UseReposListPullRequestsAssociatedWithCommitQueryPathParams {
	queryParams: UseReposListPullRequestsAssociatedWithCommitQueryQueryParams;
}

/**
 * Lists all pull requests containing the provided commit SHA, which can be from any point in the commit history. The results will include open and closed pull requests. Additional preview headers may be required to see certain details for associated pull requests, such as whether a pull request is in a draft state. For more information about previews that might affect this endpoint, see the [List pull requests](https://docs.github.com/rest/reference/pulls#list-pull-requests) endpoint.
 */

export function useReposListPullRequestsAssociatedWithCommitQuery(
	props: UseReposListPullRequestsAssociatedWithCommitQueryProps,
) {
	const { owner, repo, commit_sha, queryParams } = props;

	return useQuery([
		'repos/list-pull-requests-associated-with-commit',
		owner,
		repo,
		commit_sha,
		queryParams,
	]);
}
