/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';
export interface ReposListForAuthenticatedUserQueryParams {
	visibility?: 'all' | 'private' | 'public';
	affiliation?: string;
	type?: 'all' | 'member' | 'owner' | 'private' | 'public';
	sort?: 'created' | 'full_name' | 'pushed' | 'updated';
	direction?: 'asc' | 'desc';
	per_page?: number;
	page?: number;
	since?: string;
	before?: string;
}

export interface UseReposListForAuthenticatedUserQueryProps {
	queryParams: ReposListForAuthenticatedUserQueryParams;
}

export function useReposListForAuthenticatedUserQuery(
	props: UseReposListForAuthenticatedUserQueryProps,
) {
	const { queryParams } = props;

	return useQuery(['repos/list-for-authenticated-user', queryParams]);
}
