/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseReposAddTeamAccessRestrictionsMutationPathParams {
	owner: string;
	repo: string;
	branch: string;
}

/**
 * @example {"teams":["my-team"]}
 */
export interface UseReposAddTeamAccessRestrictionsMutationRequestBody {
	/**
	 * teams parameter
	 */
	teams: string[];
}

export interface UseReposAddTeamAccessRestrictionsMutationProps
	extends UseReposAddTeamAccessRestrictionsMutationPathParams {
	body: UseReposAddTeamAccessRestrictionsMutationRequestBody;
}

/**
 * Protected branches are available in public repositories with GitHub Free and GitHub Free for organizations, and in public and private repositories with GitHub Pro, GitHub Team, GitHub Enterprise Cloud, and GitHub Enterprise Server. For more information, see [GitHub's products](https://help.github.com/github/getting-started-with-github/githubs-products) in the GitHub Help documentation.
 *
 * Grants the specified teams push access for this branch. You can also give push access to child teams.
 *
 * | Type    | Description                                                                                                                                |
 * | ------- | ------------------------------------------------------------------------------------------------------------------------------------------ |
 * | `array` | The teams that can have push access. Use the team's `slug`. **Note**: The list of users, apps, and teams in total is limited to 100 items. |
 */

export function useReposAddTeamAccessRestrictionsMutation(
	props: UseReposAddTeamAccessRestrictionsMutationProps,
) {
	return useMutation(() => Promise.resolve());
}
