/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface UseReposGetViewsQueryPathParams {
	owner: string;
	repo: string;
}

export interface UseReposGetViewsQueryQueryParams {
	/**
	 * @default "day"
	 */
	per?: '' | 'day' | 'week';
}

export interface UseReposGetViewsQueryProps extends UseReposGetViewsQueryPathParams {
	queryParams: UseReposGetViewsQueryQueryParams;
}

/**
 * Get the total number of views and breakdown per day or week for the last 14 days. Timestamps are aligned to UTC midnight of the beginning of the day or week. Week begins on Monday.
 */

export function useReposGetViewsQuery(props: UseReposGetViewsQueryProps) {
	const { owner, repo, queryParams } = props;

	return useQuery(['repos/get-views', owner, repo, queryParams]);
}
