/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface UseReactionsListForIssueCommentQueryPathParams {
	owner: string;
	repo: string;
	comment_id: number;
}

export interface UseReactionsListForIssueCommentQueryQueryParams {
	content?: '+1' | '-1' | 'confused' | 'eyes' | 'heart' | 'hooray' | 'laugh' | 'rocket';
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface UseReactionsListForIssueCommentQueryProps
	extends UseReactionsListForIssueCommentQueryPathParams {
	queryParams: UseReactionsListForIssueCommentQueryQueryParams;
}

/**
 * List the reactions to an [issue comment](https://docs.github.com/rest/reference/issues#comments).
 */

export function useReactionsListForIssueCommentQuery(
	props: UseReactionsListForIssueCommentQueryProps,
) {
	const { owner, repo, comment_id, queryParams } = props;

	return useQuery(['reactions/list-for-issue-comment', owner, repo, comment_id, queryParams]);
}
