/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseReposPingWebhookMutationPathParams {
	owner: string;
	repo: string;
	hook_id: number;
}

export interface UseReposPingWebhookMutationProps extends UseReposPingWebhookMutationPathParams {}

/**
 * This will trigger a [ping event](https://docs.github.com/webhooks/#ping-event) to be sent to the hook.
 */

export function useReposPingWebhookMutation(props: UseReposPingWebhookMutationProps) {
	return useMutation(() => Promise.resolve());
}
