/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseReposDeleteReleaseAssetMutationPathParams {
	owner: string;
	repo: string;
	asset_id: number;
}

export interface UseReposDeleteReleaseAssetMutationProps
	extends UseReposDeleteReleaseAssetMutationPathParams {}

/**
 *
 */

export function useReposDeleteReleaseAssetMutation(props: UseReposDeleteReleaseAssetMutationProps) {
	return useMutation(() => Promise.resolve());
}
