/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface UseReposListCommentsForCommitQueryPathParams {
	owner: string;
	repo: string;
	commit_sha: string;
}

export interface UseReposListCommentsForCommitQueryQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface UseReposListCommentsForCommitQueryProps
	extends UseReposListCommentsForCommitQueryPathParams {
	queryParams: UseReposListCommentsForCommitQueryQueryParams;
}

/**
 * Use the `:commit_sha` to specify the commit that will have its comments listed.
 */

export function useReposListCommentsForCommitQuery(props: UseReposListCommentsForCommitQueryProps) {
	const { owner, repo, commit_sha, queryParams } = props;

	return useQuery(['repos/list-comments-for-commit', owner, repo, commit_sha, queryParams]);
}
