/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface UseReposListForAuthenticatedUserQueryQueryParams {
	/**
	 * @default "all"
	 */
	visibility?: 'all' | 'private' | 'public';
	/**
	 * @default "owner,collaborator,organization_member"
	 */
	affiliation?: string;
	/**
	 * @default "all"
	 */
	type?: 'all' | 'member' | 'owner' | 'private' | 'public';
	/**
	 * @default "full_name"
	 */
	sort?: 'created' | 'full_name' | 'pushed' | 'updated';
	direction?: 'asc' | 'desc';
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
	since?: string;
	before?: string;
}

export interface UseReposListForAuthenticatedUserQueryProps {
	queryParams: UseReposListForAuthenticatedUserQueryQueryParams;
}

/**
 * Lists repositories that the authenticated user has explicit permission (`:read`, `:write`, or `:admin`) to access.
 *
 * The authenticated user has explicit permission to access repositories they own, repositories where they are a collaborator, and repositories that they can access through an organization membership.
 */

export function useReposListForAuthenticatedUserQuery(
	props: UseReposListForAuthenticatedUserQueryProps,
) {
	const { queryParams } = props;

	return useQuery(['repos/list-for-authenticated-user', queryParams]);
}
