/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface UseScimGetProvisioningInformationForUserQueryPathParams {
	org: string;
	scim_user_id: string;
}

export interface UseScimGetProvisioningInformationForUserQueryProps
	extends UseScimGetProvisioningInformationForUserQueryPathParams {}

/**
 *
 */

export function useScimGetProvisioningInformationForUserQuery(
	props: UseScimGetProvisioningInformationForUserQueryProps,
) {
	const { org, scim_user_id } = props;

	return useQuery(['scim/get-provisioning-information-for-user', org, scim_user_id]);
}
