/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';
export interface SearchCommitsQueryParams {
	q: string;
	sort?: 'author-date' | 'committer-date';
	order?: 'asc' | 'desc';
	per_page?: number;
	page?: number;
}

export interface UseSearchCommitsQueryProps {
	queryParams: SearchCommitsQueryParams;
}

export function useSearchCommitsQuery(props: UseSearchCommitsQueryProps) {
	const { queryParams } = props;

	return useQuery(['search/commits', queryParams]);
}
