/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';
export interface SearchReposQueryParams {
	q: string;
	sort?: 'forks' | 'help-wanted-issues' | 'stars' | 'updated';
	order?: 'asc' | 'desc';
	per_page?: number;
	page?: number;
}

export interface UseSearchReposQueryProps {
	queryParams: SearchReposQueryParams;
}

export function useSearchReposQuery(props: UseSearchReposQueryProps) {
	const { queryParams } = props;

	return useQuery(['search/repos', queryParams]);
}
