/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface UseTeamsListDiscussionsLegacyQueryPathParams {
	team_id: number;
}

export interface UseTeamsListDiscussionsLegacyQueryQueryParams {
	/**
	 * @default "desc"
	 */
	direction?: 'asc' | 'desc';
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface UseTeamsListDiscussionsLegacyQueryProps
	extends UseTeamsListDiscussionsLegacyQueryPathParams {
	queryParams: UseTeamsListDiscussionsLegacyQueryQueryParams;
}

/**
 * **Deprecation Notice:** This endpoint route is deprecated and will be removed from the Teams API. We recommend migrating your existing code to use the new [`List discussions`](https://docs.github.com/rest/reference/teams#list-discussions) endpoint.
 *
 * List all discussions on a team's page. OAuth access tokens require the `read:discussion` [scope](https://docs.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/).
 * @deprecated
 */

export function useTeamsListDiscussionsLegacyQuery(props: UseTeamsListDiscussionsLegacyQueryProps) {
	const { team_id, queryParams } = props;

	return useQuery(['teams/list-discussions-legacy', team_id, queryParams]);
}
