/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface TeamsGetMemberLegacyPathParams {
	team_id: number;
	username: string;
}

export interface UseTeamsGetMemberLegacyQueryProps extends TeamsGetMemberLegacyPathParams {}

/**
 * The "Get team member" endpoint (described below) is deprecated.
 *
 * We recommend using the [Get team membership for a user](https://docs.github.com/rest/reference/teams#get-team-membership-for-a-user) endpoint instead. It allows you to get both active and pending memberships.
 *
 * To list members in a team, the team must be visible to the authenticated user.
 * @deprecated
 */

export function useTeamsGetMemberLegacyQuery(props: UseTeamsGetMemberLegacyQueryProps) {
	const { team_id, username } = props;

	return useQuery(['teams/get-member-legacy', team_id, username]);
}
