/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseTeamsCreateDiscussionLegacyMutationPathParams {
	team_id: number;
}

export interface UseTeamsCreateDiscussionLegacyMutationRequestBody {
	/**
	 * The discussion post's body text.
	 */
	body: string;
	/**
	 * Private posts are only visible to team members, organization owners, and team maintainers. Public posts are visible to all members of the organization. Set to `true` to create a private post.
	 */
	private?: boolean;
	/**
	 * The discussion post's title.
	 */
	title: string;
}

export interface UseTeamsCreateDiscussionLegacyMutationProps
	extends UseTeamsCreateDiscussionLegacyMutationPathParams {
	body: UseTeamsCreateDiscussionLegacyMutationRequestBody;
}

/**
 * **Deprecation Notice:** This endpoint route is deprecated and will be removed from the Teams API. We recommend migrating your existing code to use the new [`Create a discussion`](https://docs.github.com/rest/reference/teams#create-a-discussion) endpoint.
 *
 * Creates a new discussion post on a team's page. OAuth access tokens require the `write:discussion` [scope](https://docs.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/).
 *
 * This endpoint triggers [notifications](https://docs.github.com/en/github/managing-subscriptions-and-notifications-on-github/about-notifications). Creating content too quickly using this endpoint may result in abuse rate limiting. See "[Abuse rate limits](https://docs.github.com/rest/overview/resources-in-the-rest-api#abuse-rate-limits)" and "[Dealing with abuse rate limits](https://docs.github.com/rest/guides/best-practices-for-integrators#dealing-with-rate-limits)" for details.
 * @deprecated
 */

export function useTeamsCreateDiscussionLegacyMutation(
	props: UseTeamsCreateDiscussionLegacyMutationProps,
) {
	return useMutation(() => Promise.resolve());
}
