/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseTeamsDeleteInOrgMutationPathParams {
	org: string;
	team_slug: string;
}

export interface UseTeamsDeleteInOrgMutationProps extends UseTeamsDeleteInOrgMutationPathParams {}

/**
 * To delete a team, the authenticated user must be an organization owner or team maintainer.
 *
 * If you are an organization owner, deleting a parent team will delete all of its child teams as well.
 *
 * **Note:** You can also specify a team by `org_id` and `team_id` using the route `DELETE /organizations/{org_id}/team/{team_id}`.
 */

export function useTeamsDeleteInOrgMutation(props: UseTeamsDeleteInOrgMutationProps) {
	return useMutation(() => Promise.resolve());
}
