/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface TeamsListPendingInvitationsLegacyPathParams {
	team_id: number;
}

export interface TeamsListPendingInvitationsLegacyQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface UseTeamsListPendingInvitationsLegacyQueryProps
	extends TeamsListPendingInvitationsLegacyPathParams {
	queryParams: TeamsListPendingInvitationsLegacyQueryParams;
}

/**
 * **Deprecation Notice:** This endpoint route is deprecated and will be removed from the Teams API. We recommend migrating your existing code to use the new [`List pending team invitations`](https://docs.github.com/rest/reference/teams#list-pending-team-invitations) endpoint.
 *
 * The return hash contains a `role` field which refers to the Organization Invitation role and will be one of the following values: `direct_member`, `admin`, `billing_manager`, `hiring_manager`, or `reinstate`. If the invitee is not a GitHub member, the `login` field in the return hash will be `null`.
 * @deprecated
 */

export function useTeamsListPendingInvitationsLegacyQuery(
	props: UseTeamsListPendingInvitationsLegacyQueryProps,
) {
	const { team_id, queryParams } = props;

	return useQuery(['teams/list-pending-invitations-legacy', team_id, queryParams]);
}
