/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';
export interface TeamsListPathParams {
	org: string;
}

export interface TeamsListQueryParams {
	per_page?: number;
	page?: number;
}

export interface UseTeamsListQueryProps extends TeamsListPathParams {
	queryParams: TeamsListQueryParams;
}

export function useTeamsListQuery(props: UseTeamsListQueryProps) {
	const { org, queryParams } = props;

	return useQuery(['teams/list', org, queryParams]);
}
