/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface TeamsListChildLegacyPathParams {
	team_id: number;
}

export interface TeamsListChildLegacyQueryParams {
	/**
	 * @default 30
	 */
	per_page?: number;
	/**
	 * @default 1
	 */
	page?: number;
}

export interface UseTeamsListChildLegacyQueryProps extends TeamsListChildLegacyPathParams {
	queryParams: TeamsListChildLegacyQueryParams;
}

/**
 * **Deprecation Notice:** This endpoint route is deprecated and will be removed from the Teams API. We recommend migrating your existing code to use the new [`List child teams`](https://docs.github.com/rest/reference/teams#list-child-teams) endpoint.
 * @deprecated
 */

export function useTeamsListChildLegacyQuery(props: UseTeamsListChildLegacyQueryProps) {
	const { team_id, queryParams } = props;

	return useQuery(['teams/list-child-legacy', team_id, queryParams]);
}
