/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';
export interface TeamsListDiscussionCommentsLegacyPathParams {
	team_id: number;
	discussion_number: number;
}

export interface TeamsListDiscussionCommentsLegacyQueryParams {
	direction?: 'asc' | 'desc';
	per_page?: number;
	page?: number;
}

export interface UseTeamsListDiscussionCommentsLegacyQueryProps
	extends TeamsListDiscussionCommentsLegacyPathParams {
	queryParams: TeamsListDiscussionCommentsLegacyQueryParams;
}

export function useTeamsListDiscussionCommentsLegacyQuery(
	props: UseTeamsListDiscussionCommentsLegacyQueryProps,
) {
	const { team_id, discussion_number, queryParams } = props;

	return useQuery([
		'teams/list-discussion-comments-legacy',
		team_id,
		discussion_number,
		queryParams,
	]);
}
