/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseTeamsCreateDiscussionInOrgMutationPathParams {
	org: string;
	team_slug: string;
}

export interface UseTeamsCreateDiscussionInOrgMutationRequestBody {
	/**
	 * The discussion post's body text.
	 */
	body: string;
	/**
	 * Private posts are only visible to team members, organization owners, and team maintainers. Public posts are visible to all members of the organization. Set to `true` to create a private post.
	 */
	private?: boolean;
	/**
	 * The discussion post's title.
	 */
	title: string;
}

export interface UseTeamsCreateDiscussionInOrgMutationProps
	extends UseTeamsCreateDiscussionInOrgMutationPathParams {
	body: UseTeamsCreateDiscussionInOrgMutationRequestBody;
}

/**
 * Creates a new discussion post on a team's page. OAuth access tokens require the `write:discussion` [scope](https://docs.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/).
 *
 * This endpoint triggers [notifications](https://docs.github.com/en/github/managing-subscriptions-and-notifications-on-github/about-notifications). Creating content too quickly using this endpoint may result in abuse rate limiting. See "[Abuse rate limits](https://docs.github.com/rest/overview/resources-in-the-rest-api#abuse-rate-limits)" and "[Dealing with abuse rate limits](https://docs.github.com/rest/guides/best-practices-for-integrators#dealing-with-rate-limits)" for details.
 *
 * **Note:** You can also specify a team by `org_id` and `team_id` using the route `POST /organizations/{org_id}/team/{team_id}/discussions`.
 */

export function useTeamsCreateDiscussionInOrgMutation(
	props: UseTeamsCreateDiscussionInOrgMutationProps,
) {
	return useMutation(() => Promise.resolve());
}
