/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseUsersUnfollowMutationPathParams {
	username: string;
}

export interface UseUsersUnfollowMutationProps extends UseUsersUnfollowMutationPathParams {}

/**
 * Unfollowing a user requires the user to be logged in and authenticated with basic auth or OAuth with the `user:follow` scope.
 */

export function useUsersUnfollowMutation(props: UseUsersUnfollowMutationProps) {
	return useMutation(() => Promise.resolve());
}
