/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseUsersSetPrimaryEmailVisibilityForAuthenticatedMutationRequestBody {
	/**
	 * An email address associated with the GitHub user account to manage.
	 * @example "org@example.com"
	 */
	email: string;
	/**
	 * Denotes whether an email is publically visible.
	 */
	visibility: 'private' | 'public';
}

export interface UseUsersSetPrimaryEmailVisibilityForAuthenticatedMutationProps {
	body: UseUsersSetPrimaryEmailVisibilityForAuthenticatedMutationRequestBody;
}

/**
 * Sets the visibility for your primary email addresses.
 */

export function useUsersSetPrimaryEmailVisibilityForAuthenticatedMutation(
	props: UseUsersSetPrimaryEmailVisibilityForAuthenticatedMutationProps,
) {
	return useMutation(() => Promise.resolve());
}
