/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';
export interface UsersListQueryParams {
	since?: number;
	per_page?: number;
}

export interface UseUsersListQueryProps {
	queryParams: UsersListQueryParams;
}

export function useUsersListQuery(props: UseUsersListQueryProps) {
	const { queryParams } = props;

	return useQuery(['users/list', queryParams]);
}
