/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';
export interface UsersListFollowersForUserPathParams {
	username: string;
}

export interface UsersListFollowersForUserQueryParams {
	per_page?: number;
	page?: number;
}

export interface UseUsersListFollowersForUserQueryProps
	extends UsersListFollowersForUserPathParams {
	queryParams: UsersListFollowersForUserQueryParams;
}

export function useUsersListFollowersForUserQuery(props: UseUsersListFollowersForUserQueryProps) {
	const { username, queryParams } = props;

	return useQuery(['users/list-followers-for-user', username, queryParams]);
}
