/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useQuery } from '@tanstack/react-query';

export interface UsersGetGpgKeyForAuthenticatedPathParams {
	gpg_key_id: number;
}

export interface UseUsersGetGpgKeyForAuthenticatedQueryProps
	extends UsersGetGpgKeyForAuthenticatedPathParams {}

/**
 * View extended details for a single GPG key. Requires that you are authenticated via Basic Auth or via OAuth with at least `read:gpg_key` [scope](https://docs.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/).
 */

export function useUsersGetGpgKeyForAuthenticatedQuery(
	props: UseUsersGetGpgKeyForAuthenticatedQueryProps,
) {
	const { gpg_key_id } = props;

	return useQuery(['users/get-gpg-key-for-authenticated', gpg_key_id]);
}
