/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
/**
 * Branch Short
 */
export interface BranchShort {
	commit: {
		sha: string;
		url: string;
	};
	name: string;
	protected: boolean;
}
