/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { CodeScanningAnalysisSarifId } from '../schemas/CodeScanningAnalysisSarifId';

export interface CodeScanningSarifsReceipt {
	id?: CodeScanningAnalysisSarifId;
	/**
	 * The REST API URL for checking the status of the upload.
	 * @format uri
	 */
	url?: string;
}
