/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import type { AuthorAssociation } from '../schemas/AuthorAssociation';
import type { ReactionRollup } from '../schemas/ReactionRollup';
import type { SimpleUser } from '../schemas/SimpleUser';

/**
 * Commit Comment
 */
export interface CommitComment {
	author_association: AuthorAssociation;
	body: string;
	commit_id: string;
	/**
	 * @format date-time
	 */
	created_at: string;
	/**
	 * @format uri
	 */
	html_url: string;
	id: number;
	line: number | null;
	node_id: string;
	path: string | null;
	position: number | null;
	reactions?: ReactionRollup;
	/**
	 * @format date-time
	 */
	updated_at: string;
	/**
	 * @format uri
	 */
	url: string;
	user: SimpleUser | null;
}
