/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

/**
 * Project columns contain cards of work.
 */
export interface ProjectColumn {
	/**
	 * @format uri
	 * @example "https://api.github.com/projects/columns/367/cards"
	 */
	cards_url: string;
	/**
	 * @format date-time
	 * @example "2016-09-05T14:18:44Z"
	 */
	created_at: string;
	/**
	 * The unique identifier of the project column
	 * @example 42
	 */
	id: number;
	/**
	 * Name of the project column
	 * @example "Remaining tasks"
	 */
	name: string;
	/**
	 * @example "MDEzOlByb2plY3RDb2x1bW4zNjc="
	 */
	node_id: string;
	/**
	 * @format uri
	 * @example "https://api.github.com/projects/120"
	 */
	project_url: string;
	/**
	 * @format date-time
	 * @example "2016-09-05T14:22:28Z"
	 */
	updated_at: string;
	/**
	 * @format uri
	 * @example "https://api.github.com/projects/columns/367"
	 */
	url: string;
}
