/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import type { SimpleUser } from '../schemas/SimpleUser';

/**
 * Repository Collaborator Permission
 */
export interface RepositoryCollaboratorPermission {
	permission: string;
	user: SimpleUser | null;
}
