/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
/**
 * Simple Commit
 */
export interface SimpleCommit {
	author: {
		email: string;
		name: string;
	} | null;
	committer: {
		email: string;
		name: string;
	} | null;
	id: string;
	message: string;
	/**
	 * @format date-time
	 */
	timestamp: string;
	tree_id: string;
}
