/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { SimpleUser } from '../schemas/SimpleUser';

/**
 * Stargazer
 */
export interface Stargazer {
	/**
	 * @format date-time
	 */
	starred_at: string;
	user: SimpleUser | null;
}
