/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.

/**
 * A topic aggregates entities that are related to a subject.
 */
export interface Topic {
	names: string[];
}
