/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
/**
 * Validation Error Simple
 */
export interface ValidationErrorSimple {
	documentation_url: string;
	errors?: string[];
	message: string;
}
