/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
/**
 * Workflow Usage
 */
export interface WorkflowUsage {
	billable: {
		MACOS?: {
			total_ms?: number;
		};
		UBUNTU?: {
			total_ms?: number;
		};
		WINDOWS?: {
			total_ms?: number;
		};
	};
}
