/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseDeleteUserMutationPathParams {
	username: string;
}

export interface UseDeleteUserMutationProps extends UseDeleteUserMutationPathParams {}

/**
 * This can only be done by the logged in user.
 */

export function useDeleteUserMutation(props: UseDeleteUserMutationProps) {
	return useMutation(() => Promise.resolve());
}
