/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseUploadFileMutationPathParams {
	/**
	 * @format int64
	 */
	petId: number;
}

export interface UseUploadFileMutationQueryParams {
	additionalMetadata?: string;
}

export interface UseUploadFileMutationProps extends UseUploadFileMutationPathParams {
	queryParams: UseUploadFileMutationQueryParams;
}

/**
 *
 */

export function useUploadFileMutation(props: UseUploadFileMutationProps) {
	return useMutation(() => Promise.resolve());
}
