/* eslint-disable */
// This code is autogenerated using @oa2ts/cli.
// Please do not modify this code directly.
import { useMutation } from '@tanstack/react-query';

export interface UseUpdatePetWithFormMutationPathParams {
	/**
	 * @format int64
	 */
	petId: number;
}

export interface UseUpdatePetWithFormMutationQueryParams {
	name?: string;
	status?: string;
}

export interface UseUpdatePetWithFormMutationProps extends UseUpdatePetWithFormMutationPathParams {
	queryParams: UseUpdatePetWithFormMutationQueryParams;
}

/**
 *
 */

export function useUpdatePetWithFormMutation(props: UseUpdatePetWithFormMutationProps) {
	return useMutation(() => Promise.resolve());
}
